ejb-core/channels/src/main/java/com/stratelia/silverpeas/notificationserver/channel/smtp/SMTPListener.java
lib-core/pom.xml
lib-core/src/main/java/com/stratelia/silverpeas/notificationManager/NotificationMetaData.java
lib-core/src/main/java/org/silverpeas/authentication/password/ForgottenPasswordMailManager.java
lib-core/src/main/java/org/silverpeas/mail/MailAddress.java
lib-core/src/main/java/org/silverpeas/mail/MailContent.java
lib-core/src/main/java/org/silverpeas/mail/MailSending.java
lib-core/src/main/java/org/silverpeas/mail/MailToSend.java
lib-core/src/main/java/org/silverpeas/mail/ReceiverMailAddressSet.java
lib-core/src/main/java/org/silverpeas/mail/engine/MailSender.java
lib-core/src/main/java/org/silverpeas/mail/engine/MailSenderProvider.java
lib-core/src/main/java/org/silverpeas/mail/engine/MailSenderThread.java
lib-core/src/main/java/org/silverpeas/mail/engine/SmtpConfiguration.java
lib-core/src/main/java/org/silverpeas/mail/engine/SmtpMailSendReportListener.java
lib-core/src/main/java/org/silverpeas/mail/engine/SmtpMailSender.java
lib-core/src/test/java/com/silverpeas/util/MailUtilTest.java
lib-core/src/test/java/org/silverpeas/cache/service/VolatileResourceCacheServiceTest.java
lib-core/src/test/java/org/silverpeas/mail/MailAddressTest.java
lib-core/src/test/java/org/silverpeas/mail/MailContentTest.java
lib-core/src/test/java/org/silverpeas/mail/ReceiverMailAddressSetTest.java
lib-core/src/test/java/org/silverpeas/mail/SmtpMailSendingMassiveTest.java
lib-core/src/test/java/org/silverpeas/mail/SmtpMailSendingTest.java
lib-core/src/test/resources/org/silverpeas/notificationserver/channel/smtp/smtpSettings.properties

All treatments that has to send mails must use this new API.
Don't forget to check linked PR https://github.com/Silverpeas/Silverpeas-Components/pull/368.

Feature #6230 - Mail Sending API

---

lib-core/src/main/java/com/silverpeas/util/template/SilverpeasStringTemplate.java
lib-core/src/main/java/com/stratelia/silverpeas/notificationManager/NotificationMetaData.java
war-core/src/main/webapp/util/javaScript/silverpeas.js

- adding new functions isDefined() and isNotDefined() on JavaScript String prototype
- fixing a little problem of detection of not defined extra messages on notification
- setting string template attribute to null value when the value is a not defined string
Please also take into account PR https://github.com/Silverpeas/Silverpeas-Components/pull/370.

Bug #6257:

---

war-core/src/main/webapp/util/javaScript/silverpeas-userZoom.js

- trying to improve the mechanism to render the popin (indicator that the popin will be displayed and the delay itself is set to 750ms instead of 1500ms)
- adjusting the computing of the position of the tooltip

Feature #6283 :

---

lib-core/src/main/java/com/silverpeas/wysiwyg/dynamicvalue/dao/DynamicValueDAO.java
lib-core/src/main/java/com/silverpeas/wysiwyg/dynamicvalue/pool/ConnectionPoolFactory.java
lib-core/src/main/java/com/stratelia/webactiv/beans/admin/dao/GroupDAO.java
lib-core/src/main/java/com/stratelia/webactiv/beans/admin/dao/UserDAO.java
lib-core/src/main/java/com/stratelia/webactiv/organization/DomainTable.java

fixing bug #6383 dynamic values on wysiwyg editor
fixing bug #6408 domain
fixing bug #6403 userpanel

Bug 6383, 6408 and 6403

---

war-core/src/main/java/org/silverpeas/web/filter/InternetExplorerAntiCompatibilityFilter.java
war-core/src/main/webapp/WEB-INF/web.xml

The code was reported from the source base of Silverpeas 6.0
[Issue in Redmine](https://tracker.silverpeas.org/issues/6200)

Add a filter to forbid the compatibility mode of IE web browsers

---

config-core/src/main/config/properties/org/silverpeas/workflowdesigner/settings/workflowDesigner.properties
lib-core/src/main/java/com/silverpeas/export/ExportDescriptor.java
lib-core/src/main/java/com/silverpeas/export/ical/ical4j/Html.java
lib-core/src/main/java/com/silverpeas/export/ical/ical4j/ICal4JICalCodec.java
lib-core/src/main/java/com/silverpeas/form/TypeManager.java
war-core/src/main/java/com/silverpeas/workflowdesigner/control/WorkflowDesignerSessionController.java
war-core/src/main/java/com/silverpeas/workflowdesigner/servlets/WorkflowDesignerRequestRouter.java
war-core/src/main/webapp/attachment/jsp/editAttachedFiles.jsp
war-core/src/main/webapp/workflowDesigner/jsp/editInput.jsp
war-core/src/main/webapp/workflowDesigner/jsp/editItem.jsp
web-core/src/main/java/com/stratelia/webactiv/util/viewGenerator/html/arrayPanes/ArrayCellSelect.java
web-core/src/main/java/com/stratelia/webactiv/util/viewGenerator/html/arrayPanes/ArrayLine.java

Some bugs fixes : 6130, 6612, 6615 and 6637

---

ejb-core/publication/src/main/java/com/stratelia/webactiv/util/publication/control/PublicationBmEJB.java
lib-core/src/main/java/org/silverpeas/search/indexEngine/model/FileDescription.java
lib-core/src/main/java/org/silverpeas/search/indexEngine/model/FullIndexEntry.java
lib-core/src/main/java/org/silverpeas/search/indexEngine/model/IndexManager.java
lib-core/src/main/java/org/silverpeas/search/indexEngine/model/IndexerThread.java
web-core/src/main/java/com/stratelia/webactiv/applicationIndexer/control/ApplicationIndexer.java

- removing call which duplicates indexation of files attached to publications
- improving indexation service to manage correctly massive requests (of indexation)

Bug #6687 fixed

---

war-core/src/main/java/org/silverpeas/web/filter/HttpServletRequestDecoration.java

When jQuery AJAX requests are sent with no caching clause, the request is nevertheless stored into the cache.
This commit proposes a way to get an appropriate management of this kind of request.
(IEFix are also performed...)

After analysing the cache of WEB browser, a problem has been detected.

---

config-core/src/main/config/properties/org/silverpeas/pdcPeas/settings/pdcPeasSettings.properties
war-core/src/main/webapp/subscription/jsp/subscriptionpanel.jsp

See commit details and tracker.silverpeas.org for further information...

Bugs fix : 6796 and 6799

---

ejb-core/formtemplate/src/main/java/com/silverpeas/workflow/engine/instance/ProcessInstanceImpl.java
lib-core/src/main/java/com/silverpeas/form/displayers/JdbcFieldDisplayer.java
lib-core/src/main/java/com/silverpeas/form/displayers/LdapFieldDisplayer.java
lib-core/src/main/java/com/silverpeas/form/fieldType/TextFieldImpl.java

See commits details...
Do not forget associated PR on Silverpeas-Components.

Fixing bugs relative to workflows and forms

---

ejb-core/formtemplate/src/main/java/com/silverpeas/workflow/engine/WorkflowEngineImpl.java
ejb-core/formtemplate/src/main/java/com/silverpeas/workflow/engine/WorkflowEngineThread.java
ejb-core/formtemplate/src/main/java/com/silverpeas/workflow/engine/instance/ProcessInstanceImpl.java
ejb-core/formtemplate/src/main/java/com/silverpeas/workflow/engine/instance/ProcessInstanceManagerImpl.java
ejb-core/formtemplate/src/main/java/com/silverpeas/workflow/engine/model/ProcessModelImpl.java
ejb-core/formtemplate/src/main/java/com/silverpeas/workflow/engine/model/ProcessModelManagerImpl.java
ejb-core/formtemplate/src/main/java/com/silverpeas/workflow/engine/user/UserSettingsImpl.java

Fixing Castor JDO create concurrency access.

Fixing Bug #6845

---

config-core/src/main/config/silvertrace/outErrorAndFatalModule.properties

Set the config of the log errorAndFatal.txt to be rolled over the weeks

Feature #5644

---

war-core/src/main/webapp/selection/jsp/userpanel.jsp
web-core/src/main/java/com/silverpeas/profile/web/UserProfileEntity.java

Display the name of each user by using the fullName method instead of computing it from its first name and its last name

bug #7118. 

---

war-core/src/main/webapp/util/javaScript/silverpeas-pdc-classification.js
war-core/src/main/webapp/util/javaScript/silverpeas-pdc-widgets.js
web-core/src/main/java/com/silverpeas/pdc/web/FilteredPdcResource.java
web-core/src/main/java/com/silverpeas/pdc/web/PdcClassificationResource.java
web-core/src/main/java/com/silverpeas/pdc/web/PdcPredefinedClassificationResource.java
web-core/src/main/java/com/silverpeas/pdc/web/PdcResource.java

When the is is only one selectable position, let it to be explicitly selected. Remove the code that autoselect a position as it broke the way the rendering mechanism of the axis' values

Bug #6947.

---

ejb-core/node/src/main/java/com/silverpeas/subscribe/util/SubscriptionUtil.java
ejb-core/node/src/test/java/com/silverpeas/subscribe/util/SubscriptionUtilTest.java
war-core/src/main/java/org/silverpeas/subscription/control/SubscriptionSessionController.java
web-core/src/main/java/com/silverpeas/subscribe/web/SubscriptionResource.java

- the domain isolation was not entirely taken in charge
- the application rights were no taken in charge when proposing the users & groups for subscription (subscription panel)

Bug #6909 - 5.14.x - fixing some wrong behaviors around the subscription management services (accessible only from kmelia application for now)

---

ejb-core/node/src/main/java/com/silverpeas/subscribe/SubscriptionService.java
ejb-core/node/src/main/java/com/silverpeas/subscribe/service/SimpleSubscriptionService.java
ejb-core/node/src/main/java/com/silverpeas/subscribe/service/SubscriptionDao.java
ejb-core/node/src/main/java/com/silverpeas/subscribe/util/SubscriptionList.java
ejb-core/node/src/main/java/com/silverpeas/subscribe/util/SubscriptionSubscriberList.java
ejb-core/node/src/main/java/com/silverpeas/subscribe/util/SubscriptionSubscriberMapBySubscriberType.java
ejb-core/node/src/main/java/com/silverpeas/subscribe/util/SubscriptionUtil.java
ejb-core/node/src/test/java/com/silverpeas/subscribe/util/SubscriptionUtilTest.java
war-core/src/main/java/org/silverpeas/subscription/control/SubscriptionSessionController.java
war-core/src/main/webapp/util/javaScript/silverpeas.js
web-core/src/main/java/com/silverpeas/subscribe/web/SubscriptionResource.java
web-core/src/main/java/com/stratelia/silverpeas/peasCore/AbstractComponentSessionController.java
web-core/src/test/java/com/silverpeas/subscribe/MockableSubscriptionService.java
web-core/src/test/java/com/silverpeas/subscribe/web/SubscriptionGettingTest.java

- the domain isolation was not entirely taken in charge
- the application rights were no taken in charge when proposing the users & groups for subscription (subscription panel)
Cleaning also some JS code.
REDMINE https://tracker.silverpeas.org/issues/6909
Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/426

Bug #6909 - 5.15.x - fixing some wrong behaviors around the subscription management services (accessible only from kmelia application for now)

---

war-core/src/main/webapp/attachment/jsp/displayAttachedFiles.jsp
web-core/src/main/java/com/stratelia/webactiv/util/viewGenerator/html/JavascriptPluginInclusion.java
web-core/src/main/java/com/stratelia/webactiv/util/viewGenerator/html/LookAndStyleTag.java
web-core/src/main/java/com/stratelia/webactiv/util/viewGenerator/html/override/LinkTag.java
web-core/src/main/java/com/stratelia/webactiv/util/viewGenerator/html/override/ScriptTag.java
web-core/src/main/resources/META-INF/viewGenerator.tld

Using it into the view of attached files.
Completing the lookAndFeel TAG with two attributes that indicates to include fieldset css and/or check form script automatically.
Linked to https://github.com/Silverpeas/Silverpeas-Components/pull/429

Adding new view tags which override script and link HTML tags in order to handle the web browser cache.

---

lib-core/src/main/java/com/silverpeas/util/FileUtil.java
lib-core/src/main/java/com/silverpeas/util/MetadataExtractor.java

Do not report this PR on Silverpeas V6.

Improving the performance significantly around the mime type detection.

---

ejb-core/contact/src/main/java/com/stratelia/webactiv/util/contact/model/ContactDetail.java
lib-core/src/main/java/org/silverpeas/util/Function.java
web-core/src/main/java/com/stratelia/webactiv/util/viewGenerator/html/arrayPanes/ArrayCellText.java
web-core/src/main/java/com/stratelia/webactiv/util/viewGenerator/html/arrayPanes/ArrayLine.java

- adding Function interface (inspired from functional interfaces of jdk1.8)
- loading by a lazily way the UserFull linked to a ContactDetail
- using new Function interface from ArrayCellText in order to give the possibility to get the text value only when necessary

Bug #1974 - fixing bad performances on massive contact displaying

---

war-core/src/main/webapp/jobDomainPeas/jsp/domainContent.jsp

But the real stuff is to start the JVM (so the server) with this parameter: -Dsilverpeas.refresh.configuration=1000

Optimizing the display of user array of administration.

---

ejb-core/formtemplate/src/main/java/com/silverpeas/form/displayers/FileFieldDisplayer.java
war-core/src/main/webapp/util/javaScript/silverpeas-tip.js
war-core/src/main/webapp/util/javaScript/silverpeas.js
war-core/src/main/webapp/util/styleSheets/jquery/jquery.qtip.css
web-core/src/main/java/org/silverpeas/contribution/web/AbstractContributionResource.java
web-core/src/main/java/org/silverpeas/contribution/web/ContributionContentResource.java
web-core/src/main/java/org/silverpeas/contribution/web/FormEntity.java

- upgrading the contribution content resource (Web service REST) in order to provide the rendered view of a form data
- adding common tool into silverpeas.js
- upgrading silverpeas-tip.js
- fixing a problem on FileFieldDisplayer when no language detected
Linked to https://github.com/Silverpeas/Silverpeas-Components/pull/451

Bug #7191 - fixing the non display of form data of resource (if any) when creating or modifying a resource reservation

---

lib-core/src/main/java/com/stratelia/webactiv/beans/admin/dao/UserSearchCriteriaForDAO.java
war-core/src/main/webapp/jobDomainPeas/jsp/groupManagers.jsp
war-core/src/main/webapp/jobStartPagePeas/jsp/roleInstance.jsp
war-core/src/main/webapp/jobStartPagePeas/jsp/spaceManager.jsp
war-core/src/main/webapp/selection/jsp/userpanel.jsp
war-core/src/main/webapp/util/javaScript/angularjs/services/silverpeas-profile.js
war-core/src/main/webapp/util/javaScript/angularjs/silverpeas-adapters.js
war-core/src/main/webapp/util/javaScript/silverpeas-user-group-list.js
war-core/src/main/webapp/util/javaScript/silverpeas.js

- making the user list and the group list be updated by a POST
- making the user sorting and group sorting more coherent between angular treatments and queries performed on the server
- adding the possibility to open a new window by performing a POST HTTP request instead of a GET in the aim to avoid getting a technical problem when passing a lot of parameters to the request
- adding into the GET method of angular adapter a mechanism which will detect if there is too much parameters for a request to send. If it is the case, the request will be split into several smaller ones...
Linked REDMINE https://tracker.silverpeas.org/issues/7581
This PR fixes also REDMINE https://tracker.silverpeas.org/issues/7535

Feature #7581 - improving performances which were very bad when dealing with a lot of users

---

war-core/src/main/webapp/util/javaScript/silverpeas-pdc.js

Using notyError() instead of classic blocking alert().

Fixing bug 7637

---

config-core/src/main/config/properties/org/silverpeas/multilang/generalMultilang.properties
config-core/src/main/config/properties/org/silverpeas/multilang/generalMultilang_fr.properties

Use feminine as GML.updatedAt and GML.publishedAt...

Fixing bug 7568

---

lib-core/src/main/java/com/silverpeas/calendar/CalendarEvent.java
lib-core/src/main/java/com/silverpeas/export/ical/ical4j/ICal4JICalCodec.java
web-core/src/main/java/com/silverpeas/ical/ExportIcalManager.java

Using eventId as part of Uid property (appId-eventId:IP_address).
So, Uid property does not change between each export.
https://tracker.silverpeas.org/issues/7586
Do not forget to check out PR on Silverpeas-Components...

[iCal] Fixing bug 7586

---

config-core/src/main/config/properties/org/silverpeas/jobStartPagePeas/multilang/jobStartPagePeasBundle.properties
config-core/src/main/config/properties/org/silverpeas/jobStartPagePeas/multilang/jobStartPagePeasBundle_en.properties
config-core/src/main/config/properties/org/silverpeas/jobStartPagePeas/multilang/jobStartPagePeasBundle_fr.properties

Renaming apps 'Administrators' into 'Managers'...
Do not forget to check out PR on Silverpeas-Components.

[UI] Fixing bug 7663

---

web-core/src/main/java/com/stratelia/silverpeas/peasCore/SessionManager.java

Present user real IP address when Silverpeas is behing a reverse proxy

Feature #2524

---

config-core/src/main/config/properties/org/silverpeas/util/security.properties
lib-core/src/main/java/org/silverpeas/util/security/SecuritySettings.java
war-core/src/main/webapp/wysiwyg/jsp/htmlEditor.jsp
web-core/src/main/java/org/silverpeas/web/filter/MassiveWebSecurityFilter.java
web-core/src/test/java/org/silverpeas/web/filter/MassiveWebSecurityFilterTest.java
web-core/src/test/resources/org/silverpeas/util/security.properties

- apply modifications done for Silverpeas V6 around WebPages and multipart request (no verification in that case)
- adding some settings in order to get a finest way to activate or deactivate security
- closing the progress message popin when getting an error on htmlEditor (displaying it also)

Massive Web Security Filter

---

lib-core/src/main/java/com/silverpeas/jcrutil/SilverpeasJcrWebdavContext.java
lib-core/src/main/java/com/silverpeas/jcrutil/converter/ConverterUtil.java
lib-core/src/main/java/org/silverpeas/attachment/model/SimpleDocument.java
lib-core/src/main/java/org/silverpeas/attachment/webdav/impl/WebdavDocumentRepository.java
lib-core/src/test/java/com/silverpeas/jcrutil/SilverpeasJcrWebdavContextTest.java
lib-core/src/test/java/com/silverpeas/jcrutil/converter/TestConverterUtil.java
lib-core/src/test/java/org/silverpeas/attachment/model/SimpleDocumentTest.java
web-core/src/main/java/com/silverpeas/jcrutil/servlets/SilverpeasJcrWebdavServlet.java

It was due to several problems:
- all WebDav request were not well handled (wrong path interpretation)
- all the illegal JCR characters were not entirely well handled...
REDMINE https://tracker.silverpeas.org/issues/7935

Bug #7935 - fixing a read-only behavior encountered into environment of some clients.

---

war-core/src/main/webapp/util/styleSheets/globalSP_SilverpeasV5.css

Répare : "En édition les champs des formulaires bougent quand on clique dessus" lié a un pull request sur component

fix bug #7966

---

core-war/src/main/webapp/util/javaScript/silverpeas-layout.js
core-web/src/main/java/org/silverpeas/core/web/look/DefaultLayoutConfiguration.java
core-web/src/main/java/org/silverpeas/core/web/look/LayoutConfiguration.java
core-web/src/main/java/org/silverpeas/core/web/look/LookHelper.java
core-web/src/main/java/org/silverpeas/core/web/look/LookSilverpeasV5Helper.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/JavascriptPluginInclusion.java

This is mandatory for developing alternative looks (like Aurora or specific ones).

[Look] Permitting to set custom JSP pages

---

lib-core/src/main/java/com/silverpeas/export/ical/ical4j/ICal4JICalCodec.java

adding VTimeZone component to explicitly define timezone

[Calendar] Fixing bug 8083

---

ejb-core/formtemplate/src/main/java/com/silverpeas/workflow/engine/instance/ProcessInstanceImpl.java

Add support for month and minute

feature #8124 : process manager - new timeOutAction delay options

---

war-core/src/main/webapp/admin/jsp/accessForbidden.jsp

Adding possibility to displaying a cause on accessForbidden page.
Do not forget to check out PR on Silverpeas-Components...

fixing bug 8192

---

core-war/src/main/webapp/util/styleSheets/globalSP_SilverpeasV5.css

liées aux boutons (user panel + bouton dans ged dans la page pour la notification forcee + les bouton de recherche qui sont souvent trop gros par rapport au champ de recherche a cote) + mise en place d un padding left pour le contenu principal pas qu il soit collé au menu à gauche

Corrections multiples css

---

core-configuration/src/main/config/data/web/weblib.war/skinBigAndAngular/basic.css
core-configuration/src/main/config/data/web/weblib.war/skinBigAndAngular/stylesheet.css
core-war/src/main/webapp/util/styleSheets/globalSP_SilverpeasV5.css

Link to last work on v6 button, templating, apparence changed by the last few tables deleted...

Css corrections

---

lib-core/src/main/java/org/silverpeas/authentication/password/ForgottenPasswordMailManager.java
lib-core/src/main/java/org/silverpeas/authentication/password/ForgottenPasswordMailParameters.java
war-core/src/main/webapp/defaultLoginQuestion.jsp
war-core/src/main/webapp/defaultReInitPassword.jsp
war-core/src/main/webapp/defaultResetPassword.jsp
web-core/src/main/java/org/silverpeas/servlets/credentials/ForgotPasswordHandler.java
web-core/src/main/java/org/silverpeas/servlets/credentials/FunctionHandler.java
web-core/src/main/java/org/silverpeas/servlets/credentials/LoginQuestionHandler.java
web-core/src/main/java/org/silverpeas/servlets/credentials/ResetPasswordHandler.java

Language of user is not used on screen and email messages...

[Authentication] Fixing bug 8504

---

config-core/src/main/config/properties/org/silverpeas/portlets/multilang/portletsBundle_de.properties
config-core/src/main/config/properties/org/silverpeas/portlets/multilang/portletsBundle_en.properties
config-core/src/main/config/properties/org/silverpeas/portlets/multilang/portletsBundle_fr.properties

Do not forget PR on Silverpeas-Components...

[Portlets] Fixing bug 8459

---

lib-core/src/main/java/com/silverpeas/form/Form.java
lib-core/src/main/java/com/silverpeas/form/displayers/WysiwygFCKFieldDisplayer.java

Do not forget to check out associated PR on Silverpeas-Components

[Templates] Fixing bugs 8460 and 8540

---

lib-core/src/main/java/com/silverpeas/form/record/GenericRecordSet.java

Removing files associated to removed form instead of deleting them directly

[Templates] Fixing bug 8625 

---

core-library/src/main/java/org/silverpeas/core/admin/service/Admin.java
core-library/src/main/java/org/silverpeas/core/admin/user/UserManager.java
core-library/src/main/java/org/silverpeas/core/security/authentication/AuthenticationService.java

- adding warning logs instead of logging the entire stack trace on id conversions
- using SilverLogger instead of SilverTrace into AuthenticationService
- fixing some sonar feedback

Bug #8629 - fixing technical errors around administration services.

---

core-api/src/main/java/org/silverpeas/core/notification/sse/ServerEvent.java
core-services/silverstatistics/src/main/java/org/silverpeas/core/silverstatistics/volume/service/SilverStatisticsManager.java

- fixing sonar feedback
- wiring SilverLogger

bug-8723: fixing the statistics scheduler which was not able to execute properly the jobs!!!

---

core-library/src/main/java/org/silverpeas/core/cache/service/VolatileResourceCacheService.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/AbstractForm.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/Form.java
core-library/src/main/java/org/silverpeas/core/security/authorization/PublicationAccessController.java
core-library/src/test/java/org/silverpeas/core/security/authorization/TestPublicationAccessController.java
core-library/src/test/java/org/silverpeas/core/security/authorization/TestSimpleDocumentAccessController.java

Do not forget to checkout PR on Components...

Closing feature 8735 : create a full publication in a single page

---

core-war/src/main/webapp/util/styleSheets/fieldset.css
core-war/src/main/webapp/util/styleSheets/globalSP_SilverpeasV5.css

Do not omit to checkout Silverpeas-Components...

[FAQ] Relative to feature 3265 : adding some CSS stuff to display filters

---

core-war/src/main/webapp/util/styleSheets/globalSP_SilverpeasV5.css

mauvais héritage de la propriété flex

Fix Bug #8961

---

core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/JdbcSqlQuery.java
core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/SplitExecuteProcess.java
core-api/src/main/java/org/silverpeas/core/util/CollectionUtil.java
core-api/src/test/java/org/silverpeas/core/util/CollectionUtilTest.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/filter/FilterManager.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/filter/RecordFilter.java
core-services/personalOrganizer/src/main/java/org/silverpeas/core/personalorganizer/model/Priority.java
core-services/personalOrganizer/src/main/java/org/silverpeas/core/personalorganizer/service/AttendeeDAO.java
core-services/personalOrganizer/src/main/java/org/silverpeas/core/personalorganizer/service/DefaultCalendarService.java
core-services/personalOrganizer/src/main/java/org/silverpeas/core/personalorganizer/service/SilverpeasCalendar.java
core-services/personalOrganizer/src/main/java/org/silverpeas/core/personalorganizer/service/ToDoDAO.java
core-services/workflow/src/main/java/org/silverpeas/core/workflow/api/ProcessInstanceManager.java
core-services/workflow/src/main/java/org/silverpeas/core/workflow/engine/instance/ProcessInstanceImpl.java
core-services/workflow/src/main/java/org/silverpeas/core/workflow/engine/instance/ProcessInstanceManagerImpl.java
core-services/workflow/src/main/java/org/silverpeas/core/workflow/engine/timeout/TimeoutManagerImpl.java
core-services/workflow/src/main/java/org/silverpeas/core/workflow/util/WorkflowUtil.java
core-services/workflow/src/main/resources/META-INF/workflowFunctions.tld
core-war/src/main/java/org/silverpeas/web/todo/control/ToDoHeaderUIEntity.java
core-war/src/main/java/org/silverpeas/web/todo/control/ToDoSessionController.java
core-war/src/main/java/org/silverpeas/web/todo/servlets/TodoRequestRouter.java
core-war/src/main/webapp/todo/jsp/checkTodo.jsp
core-war/src/main/webapp/todo/jsp/todo.jsp
core-web/src/main/java/org/silverpeas/core/web/admin/migration/UIUserCache.java
core-web/src/main/java/org/silverpeas/core/web/util/SelectableUIEntity.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/arraypanes/ArrayColumn.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/arraypanes/ArrayColumnTag.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/arraypanes/ArrayLinesTag.java
core-web/src/main/resources/META-INF/silverFunctions.tld
core-web/src/test/java/org/silverpeas/core/web/admin/migration/UIUserCacheTest.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/560

Optimizing the performances about the display of the WorkFlow process list and also about the todo list.

---

core-library/src/main/java/org/silverpeas/core/admin/domain/DomainDriverManager.java
core-library/src/main/java/org/silverpeas/core/admin/service/Admin.java
core-library/src/main/java/org/silverpeas/core/admin/user/GroupManager.java
core-library/src/main/java/org/silverpeas/core/admin/user/UserManager.java
core-library/src/main/java/org/silverpeas/core/admin/user/dao/GroupSearchCriteriaForDAO.java
core-library/src/main/java/org/silverpeas/core/admin/user/dao/UserSearchCriteriaForDAO.java
core-library/src/main/java/org/silverpeas/core/admin/user/model/GroupsSearchCriteria.java
core-library/src/main/java/org/silverpeas/core/admin/user/model/SearchCriteria.java
core-library/src/main/java/org/silverpeas/core/admin/user/model/UserDetailsSearchCriteria.java
core-war/src/main/java/org/silverpeas/web/directory/control/DirectorySessionController.java
core-war/src/main/java/org/silverpeas/web/directory/servlets/DirectoryRequestRouter.java
core-war/src/main/webapp/WEB-INF/tags/silverpeas/util/selectUsersAndGroups.tag
core-war/src/main/webapp/directory/jsp/directory.jsp
core-war/src/main/webapp/util/javaScript/silverpeas-user-group-list.js
core-war/src/main/webapp/util/styleSheets/silverpeas-calendar.css
core-web/src/main/java/org/silverpeas/core/webapi/profile/UserGroupsSearchCriteriaBuilder.java
core-web/src/main/java/org/silverpeas/core/webapi/profile/UserProfileResource.java
core-web/src/main/java/org/silverpeas/core/webapi/profile/UserProfileService.java
core-web/src/main/java/org/silverpeas/core/webapi/profile/UserProfilesSearchCriteriaBuilder.java

Check out PR on Silverpeas-Looks...

amending feature #9190 - adding domains and groups filters

---

core-configuration/src/main/config/properties/org/silverpeas/multilang/generalMultilang.properties
core-configuration/src/main/config/properties/org/silverpeas/multilang/generalMultilang_de.properties
core-configuration/src/main/config/properties/org/silverpeas/multilang/generalMultilang_en.properties
core-configuration/src/main/config/properties/org/silverpeas/multilang/generalMultilang_fr.properties
core-library/src/main/java/org/silverpeas/core/contribution/content/form/record/GenericDataRecord.java

Do not forget to check out PR on Components...

[Feature 6317] - exporting all requests of a given form

---

core-war/src/main/webapp/attachment/jsp/displayAttachedFiles.jsp

So, in a first time, the language selection is deactivated on modification.
The content language of the attachment is set one time at all on creation process.

Translations on attachment is very ambiguous.

---

core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/WysiwygFCKFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/form/XmlForm.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/record/GenericRecordSet.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/wysiwyg/WysiwygTag.java

Do not forget PR on Silverpeas-Components...

Fixing bug about i18n and WYSIWYG field

---

core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/WysiwygFCKFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/form/XmlForm.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/record/GenericRecordSet.java
core-war/src/main/webapp/templateDesigner/jsp/welcome.jsp
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/wysiwyg/WysiwygTag.java

Linked to PR: https://github.com/Silverpeas/Silverpeas-Components/pull/581

Bug 9095 8676 9268 9439 report

---

core-library/src/main/java/org/silverpeas/core/contribution/content/form/DataRecordUtil.java
core-services/workflow/src/main/java/org/silverpeas/core/workflow/api/instance/ProcessInstance.java
core-services/workflow/src/main/java/org/silverpeas/core/workflow/engine/instance/ProcessInstanceImpl.java

[Workflow] Feature 8906

---

core-library/src/main/java/org/silverpeas/core/util/URLUtil.java

Report of the fix into the master branch

Bug #9747: fixing a wrong resolution of http base url

---

core-services/contact/src/main/java/org/silverpeas/core/contact/service/DefaultContactService.java
core-web/src/main/java/org/silverpeas/core/web/export/ExportServlet.java

fixing a NullPointerException during export too
fixing Sonar issues
Please, check PR on Silverpeas-Components too...

[Yellowpages] fixing bug 9630

---

core-services/silverstatistics/src/main/java/org/silverpeas/core/silverstatistics/access/dao/HistoryObjectDAO.java

fixing some SonarLink issues too

[Statistics] fixing bug 9745

---

core-configuration/src/main/config/properties/org/silverpeas/homePage/multilang/homePageBundle.properties
core-configuration/src/main/config/properties/org/silverpeas/homePage/multilang/homePageBundle_de.properties
core-configuration/src/main/config/properties/org/silverpeas/homePage/multilang/homePageBundle_en.properties
core-configuration/src/main/config/properties/org/silverpeas/homePage/multilang/homePageBundle_fr.properties
core-configuration/src/main/config/properties/org/silverpeas/index/search/searchEngineSettings.properties
core-library/src/integration-test/java/org/silverpeas/core/admin/StubbedAdministration.java
core-library/src/main/java/org/silverpeas/core/admin/service/Admin.java
core-library/src/main/java/org/silverpeas/core/admin/service/AdminController.java
core-library/src/main/java/org/silverpeas/core/admin/service/Administration.java
core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexEngineProxy.java
core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexManager.java
core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexProcessor.java
core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexReadersCache.java
core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexerTask.java
core-library/src/main/java/org/silverpeas/core/index/search/model/IndexSearcher.java
core-war/src/main/java/org/silverpeas/web/todo/TodoIndexer.java
core-web/src/main/java/org/silverpeas/core/web/index/AbstractIndexer.java
core-web/src/main/java/org/silverpeas/core/web/index/ApplicationDYMIndexer.java
core-web/src/main/java/org/silverpeas/core/web/index/IndexationProcessExecutor.java
core-web/src/main/java/org/silverpeas/core/web/index/components/ApplicationIndexer.java
core-web/src/main/java/org/silverpeas/core/web/index/components/ComponentIndexation.java
core-web/src/main/java/org/silverpeas/core/web/index/components/ComponentIndexerAdapter.java
core-web/src/main/java/org/silverpeas/core/web/index/tools/PersonalToolIndexation.java
core-web/src/main/java/org/silverpeas/core/web/tools/agenda/AgendaIndexer.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/596

Feature #9852 : index robustness

---

core-library/src/main/java/org/silverpeas/core/io/media/image/ImageInfoType.java
core-library/src/main/java/org/silverpeas/core/io/media/image/imagemagick/Im4javaImageTool.java
core-library/src/main/java/org/silverpeas/core/io/media/image/option/AbstractImageToolOption.java
core-library/src/main/java/org/silverpeas/core/io/media/image/option/CompositionOperation.java
core-library/src/main/java/org/silverpeas/core/io/media/image/option/Margins.java
core-library/src/main/java/org/silverpeas/core/io/media/image/option/Orientation.java
core-library/src/main/java/org/silverpeas/core/io/media/image/option/OrientationOption.java
core-library/src/main/java/org/silverpeas/core/io/media/image/option/WatermarkImageOption.java
core-library/src/main/java/org/silverpeas/core/util/HttpUtil.java

Linked to PR: https://github.com/Silverpeas/Silverpeas-Components/pull/604

Feature #3371 & #9944: orientation of picture and image watermarking.

---

core-library/src/integration-test/java/org/silverpeas/core/contribution/publication/service/PublicationDAOIT.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/PublicationDAO.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/PublicationFatherDAO.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/SeeAlsoDAO.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/model/CompletePublication.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/model/Link.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/service/DefaultPublicationService.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/service/PublicationService.java
core-web/src/main/java/org/silverpeas/core/webapi/publication/PublicationResource.java

On the occasion of this feature, removing some useless and very old code on publication service

[Documents] Optimizing "See Also" feature

---

core-configuration/src/main/config/properties/org/silverpeas/util/attachment/Attachment.properties
core-library/src/main/java/org/silverpeas/core/contribution/attachment/util/AttachmentSettings.java
core-war/src/main/webapp/media/jsp/pdf/viewer.min.js
core-war/src/main/webapp/userCalendar/jsp/occurrenceView.jsp
core-war/src/main/webapp/util/javaScript/silverpeas-view.js
core-war/src/main/webapp/util/javaScript/silverpeas.js
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/JavascriptPluginInclusion.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/JavascriptSettingProducer.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/613

Feature #5778: wiring components almanach, userCalenda, questionReply, suggestionBox, forums, projectManager and resourcesManager.

---

core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/DefaultJdbcSqlExecutor.java
core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/JdbcSqlQuery.java
core-api/src/main/java/org/silverpeas/core/util/StringUtil.java
core-war/src/main/webapp/util/javaScript/silverpeas.js

Don't forget to merge also PR:
https://github.com/Silverpeas/Silverpeas-Assembly/pull/16
https://github.com/Silverpeas/Silverpeas-Components/pull/614

Feature 9990

---

core-war/src/main/webapp/POPUP/jsp/readMessage.jsp
core-war/src/main/webapp/SILVERMAIL/jsp/readMessage.jsp
core-war/src/main/webapp/SILVERMAIL/jsp/readSentNotification.jsp
core-war/src/main/webapp/jobStartPagePeas/jsp/componentInfo.jsp
core-war/src/main/webapp/util/javaScript/progressMessage.js
core-war/src/main/webapp/util/javaScript/silverpeas-layout.js
core-war/src/main/webapp/util/javaScript/silverpeas-user-session.js
core-war/src/main/webapp/util/javaScript/silverpeas-window.js
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/WebCommonLookAndFeel.java

Fixing a wrong behavior on Silverpeas's link specified on Link HTMLElement with target attribute filled with blank value.
Fixing technical layout management when using progressMessage on opened Window.

Bug #10135 and #10136.

---

core-api/src/main/java/org/silverpeas/core/cache/service/InMemoryCache.java
core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/DefaultJdbcSqlExecutor.java
core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/JdbcSqlQuery.java
core-api/src/main/java/org/silverpeas/core/util/ListSlice.java
core-configuration/src/main/config/properties/org/silverpeas/general.properties
core-library/src/integration-test/java/org/silverpeas/core/contribution/publication/service/LastPublicationDAOIT.java
core-library/src/integration-test/java/org/silverpeas/core/persistence/jdbc/JdbcSqlQueryIT.java
core-library/src/integration-test/resources/org/silverpeas/general.properties
core-library/src/main/java/org/silverpeas/core/admin/user/dao/GroupSearchCriteriaForDAO.java
core-library/src/main/java/org/silverpeas/core/admin/user/dao/UserSearchCriteriaForDAO.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/PublicationDAO.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/service/DefaultPublicationService.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/service/PublicationService.java
core-library/src/main/java/org/silverpeas/core/util/Pagination.java
core-library/src/test/java/org/silverpeas/core/util/PaginationTest.java
core-war/src/main/java/org/silverpeas/web/portlets/portal/SPDesktopServlet.java

Completing the pagination mechanism with process feature which permits to combines pagination on a data source with functional pagination.
Optimizing the loading of publications into context of news feed.
Modifying publication DAO in order to use pagination.
Fixing also a little problem about the space context on personal space rendering (with all portlets).
Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/622

Trying to optimize the loading of publications.

---

core-library/src/main/java/org/silverpeas/core/notification/user/client/DefaultNotificationManager.java

Fix the NullPointerException bug when sending an email to the newly user

Fix bug #10436

---

core-library/src/main/java/org/silverpeas/core/html/PermalinkRegistry.java
core-library/src/main/java/org/silverpeas/core/util/URLUtil.java
core-library/src/test/java/org/silverpeas/core/html/PermalinkRegistryTest.java
core-war/src/main/java/org/silverpeas/web/portlets/portal/SPDesktopServlet.java
core-war/src/main/webapp/util/javaScript/silverpeas-admin-window.js
core-war/src/main/webapp/util/javaScript/silverpeas-window.js
core-war/src/main/webapp/util/jsp/safeContentRedirection.jsp
core-web/src/main/java/org/silverpeas/core/web/http/SafeContentRedirect.java
core-web/src/main/java/org/silverpeas/core/web/http/ServletSafeContentRedirect.java
core-web/src/main/java/org/silverpeas/core/web/mvc/route/DefaultComponentInstanceRoutingMap.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/JavascriptPluginInclusion.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/JavascriptSettingProducer.java

Adding a registry of permalink which is now shared with SilverpeasWindow plugin in charge of the management of lazy loading in order to get the same knowledgement about permalink detection.

Fixing cross domain problems which could happen when a specific URL is set as content source of space homepage.

---

Jenkinsfile

Linked to PR:
- https://github.com/Silverpeas/Silverpeas-Components/pull/650
- https://github.com/Silverpeas/Silverpeas-Looks/pull/38

Feature #26: Trying to manage a lock file in order to handle build dependencies.

---

core-war/src/main/webapp/util/javaScript/silverpeas-layout.js
core-war/src/main/webapp/util/javaScript/silverpeas-window.js

This feature implies the upgrading of SilverpeasLayout plugin which is now able to hide "surely" a part of the layout. Hiding "surely"a part of the layout means that before a delay (parameterizable, 500ms by default) it is not possible to show a part of layout if it has been "surely" hidden.
SilverpeasLayout provides also the possibility to show "surely" a part of the layout.
This evolution has been done after the discover of direct external or non standard URLs provided on Silverpeas's page which require to display the linked content without the Silverpeas's navigation part.
But using this kind of URL can make the UI of Silverpeas crashing according to recent security evolutions implemented into WEB browsers.
So, the idea is to use hyperlink component for external or non standard page …

Feature #9796: it is now possible to hide the navigation part of the layout from load services provided by SilverpeasWindow plugin.

---

core-library/src/main/java/org/silverpeas/core/contribution/content/form/Util.java
core-library/src/main/java/org/silverpeas/core/util/URLUtil.java
core-war/src/main/java/org/silverpeas/web/filter/ResourceCacheFilter.java
core-war/src/main/webapp/WEB-INF/web.xml
core-web/src/main/java/org/silverpeas/core/web/util/WysiwygEditorConfig.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/JavascriptPluginInclusion.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/WebCommonLookAndFeel.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/override/LoadScriptTag.java

This is improving significantly the displaying performances!!!

Feature #10638 : adding management of Cache Busting by fingerprint method on CSS and JS files provided by Silverpeas application.

---

core-configuration/src/main/config/properties/org/silverpeas/admin/roleMapping.properties
core-war/src/main/webapp/util/javaScript/silverpeas-responsibles.js
core-web/src/main/java/org/silverpeas/core/webapi/admin/AbstractAdminResource.java
core-web/src/main/java/org/silverpeas/core/webapi/admin/ComponentEntity.java
core-web/src/main/java/org/silverpeas/core/webapi/admin/SpaceAppearanceEntity.java
core-web/src/main/java/org/silverpeas/core/webapi/admin/SpaceEntity.java

- fixing a regression on resource URI computing around space and component WEB services
- adding manager role to webPages component without data recovery
- fixing silverpeas-responsibles plugin in order to detect more accurately empty role data
Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/681

Bug #10897: fixing some stuffs discovered around WebPages component

---

core-web/src/main/java/org/silverpeas/core/web/http/FileResponse.java
core-web/src/main/java/org/silverpeas/core/web/http/RestFileResponse.java
core-web/src/main/java/org/silverpeas/core/web/http/ServletFileResponse.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/685

Bug #11287: adding the possibility to specify a download context to FileResponse API.

---

core-configuration/src/main/config/properties/org/silverpeas/form/multilang/formBundle.properties
core-configuration/src/main/config/properties/org/silverpeas/form/multilang/formBundle_de.properties
core-configuration/src/main/config/properties/org/silverpeas/form/multilang/formBundle_en.properties
core-configuration/src/main/config/properties/org/silverpeas/form/multilang/formBundle_fr.properties
core-configuration/src/main/config/properties/org/silverpeas/templatedesigner/multilang/templateDesignerBundle_de.properties
core-configuration/src/main/config/properties/org/silverpeas/templatedesigner/multilang/templateDesignerBundle_en.properties
core-configuration/src/main/config/properties/org/silverpeas/templatedesigner/multilang/templateDesignerBundle_fr.properties
core-library/src/main/java/org/silverpeas/core/contribution/content/form/AbstractForm.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/PagesContext.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/form/HtmlForm.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/form/XmlForm.java
core-library/src/main/java/org/silverpeas/core/contribution/template/publication/PublicationTemplate.java
core-library/src/main/java/org/silverpeas/core/contribution/template/publication/PublicationTemplateImpl.java
core-library/src/main/java/org/silverpeas/core/contribution/template/publication/PublicationTemplateManager.java
core-war/src/main/java/org/silverpeas/web/socialnetwork/myprofil/control/MyProfilSessionController.java
core-war/src/main/java/org/silverpeas/web/templatedesigner/control/TemplateDesignerSessionController.java
core-war/src/main/java/org/silverpeas/web/templatedesigner/servlets/TemplateDesignerRequestRouter.java
core-war/src/main/webapp/jobDomainPeas/jsp/userCreate.jsp
core-war/src/main/webapp/socialNetwork/jsp/myProfil/myProfileTabIdentity.jsp
core-war/src/main/webapp/templateDesigner/jsp/templateHeader.jsp
core-war/src/main/webapp/util/styleSheets/silverpeas-main.css
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/DirectoryExtraFormTag.java
core-web/src/main/resources/META-INF/viewGenerator.tld

Adding the possibility to ignore form when creating a user

Feature #11631 : on directory form, adding vibility new criteria 'domains' and 'groups'

---

core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/ImageFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/template/form/service/DefaultFormTemplateService.java
core-services/importExport/src/main/java/org/silverpeas/core/importexport/attachment/AttachmentImportExport.java
core-services/importExport/src/main/java/org/silverpeas/core/importexport/control/GEDImportExport.java
core-services/importExport/src/main/java/org/silverpeas/core/importexport/control/PublicationsTypeManager.java
core-services/importExport/src/main/java/org/silverpeas/core/importexport/report/HtmlExportPublicationGenerator.java

Fixing also bugs #11640 #11661

Bug #11589 : export strengthening

---

core-library/src/main/java/org/silverpeas/core/util/URLUtil.java
core-library/src/test/java/org/silverpeas/core/util/URLUtilTest.java
core-war/src/main/java/org/silverpeas/web/AutoRedirectServlet.java
core-war/src/main/webapp/util/javaScript/lookV5/navigation.js
core-war/src/main/webapp/util/javaScript/silverpeas-layout.js
core-war/src/main/webapp/util/javaScript/silverpeas-window.js
core-war/src/main/webapp/util/javaScript/silverpeas.js
core-war/src/main/webapp/util/jsp/safeContentRedirection.jsp
core-war/src/main/webapp/webConnections/jsp/connection.jsp
core-web/src/main/java/org/silverpeas/core/web/http/HttpRequest.java
core-web/src/main/java/org/silverpeas/core/web/look/SilverpeasLook.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/LookAndStyleTag.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/WebCommonLookAndFeel.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/layout/BodyPartLayoutTag.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/layout/HeadLayoutPartTag.java
core-web/src/main/resources/META-INF/viewGenerator.tld

The UI specified on a space is now applied in any circumstances.
Applying also classes current-space-[space identifier] and current-component-[component instance identifier] on root container of a Silverpeas's layout.
Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/706

Bug 10954: improving the space appearance management.

---

core-library/src/main/java/org/silverpeas/core/util/ZipUtil.java

Adding 64 bits zip support for extending limits values.

Bug #11795

---

core-war/src/main/webapp/util/styleSheets/fieldset.css

Bug d'affichage sous chrome - Modification d'utilisation de display table et cell  pour du Flex

Fix Bug #11880 

---

core-war/src/main/webapp/wysiwyg/jsp/htmlEditor.jsp
core-web/src/main/java/org/silverpeas/core/web/mvc/route/ComponentRequestRouter.java

Bug #12104: the user language preference was not used by common HTML page into context of edition of component instance introduction.

---

core-library/src/main/java/org/silverpeas/core/security/authorization/ComponentAccessController.java
core-library/src/main/java/org/silverpeas/core/security/authorization/NodeAccessController.java
core-library/src/main/java/org/silverpeas/core/security/authorization/PublicationAccessController.java
core-library/src/test/java/org/silverpeas/core/security/authorization/TestNodeAccessController.java
core-library/src/test/java/org/silverpeas/core/security/authorization/TestPublicationAccessController.java

Adding a batch of unit test about NodeAccessController.

Bug #12171-master: adding missing authorization computing rules.

---

core-library/src/main/java/org/silverpeas/core/admin/space/quota/process/check/DataStorageQuotaProcessCheck.java
core-library/src/main/java/org/silverpeas/core/process/annotation/SimulationActionProcessAnnotationInterceptor.java
core-library/src/main/java/org/silverpeas/core/process/annotation/SimulationActionProcessProcessor.java
core-library/src/main/java/org/silverpeas/core/process/annotation/SimulationElementConversionProcess.java
core-library/src/test/java/org/silverpeas/core/process/annotation/SimulationActionProcessProcessorTest.java

IF OK, THIS PR WILL BE INTEGRATED IMMEDIATELY BY MYSELF
Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/740

Feature #12035: refactoring of simulation process in order to be used from anywhere, with several source contexts

---

core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/PublicationCriteria.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/PublicationDAO.java
core-web/src/main/java/org/silverpeas/core/webapi/node/NodeAttrEntity.java
core-web/src/main/java/org/silverpeas/core/webapi/node/NodeType.java

Do not forget https://github.com/Silverpeas/Silverpeas-Components/pull/734

Feature #12038 : adding virtual folder of non visible publications (not yet or no more visibles)

---

core-library/src/main/java/org/silverpeas/core/contribution/content/form/AbstractForm.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/Form.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/PagesContext.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/form/XmlForm.java
core-library/src/main/java/org/silverpeas/core/index/search/SimpleSearchEngine.java
core-war/src/main/java/org/silverpeas/web/pdc/control/PdcSearchSessionController.java

Do not forget to check out https://github.com/Silverpeas/Silverpeas-Components/pull/743 and https://github.com/Silverpeas/Silverpeas-Looks/pull/53

Feature #12442 : two templates for a single 'webPages' app

---

core-library/pom.xml
core-library/src/main/java/org/silverpeas/core/util/PdfUtil.java
core-services/importExport/src/main/java/org/silverpeas/core/importexport/control/ImportExport.java
pom.xml

Updating old library itext to the most recent one.
Updating Log4j to 2.15 version.
Linked to PRs:
* https://github.com/Silverpeas/silverpeas-dependencies-bom/pull/25
* https://github.com/Silverpeas/silverpeas-test-dependencies-bom/pull/7
* https://github.com/Silverpeas/Silverpeas-Project/pull/7
* https://github.com/Silverpeas/Silverpeas-Components/pull/763
* https://github.com/Silverpeas/Silverpeas-Looks/pull/56
* https://github.com/Silverpeas/Silverpeas-Assembly/pull/20
* https://github.com/Silverpeas/silverpeasmobile/pull/26

Bug #12648

---

core-library/pom.xml
core-library/src/main/java/org/silverpeas/core/util/PdfUtil.java
core-services/importExport/src/main/java/org/silverpeas/core/importexport/control/ImportExport.java
pom.xml

Updating old library itext to the most recent one.
Linked to PRs:
* https://github.com/Silverpeas/Silverpeas-Components/pull/764
* https://github.com/Silverpeas/Silverpeas-Looks/pull/57
* https://github.com/Silverpeas/silverpeasmobile/pull/27
* https://github.com/Silverpeas/Silverpeas-Assembly/pull/21

Bug #12648 / 6.3.x

---

core-war/src/main/java/org/silverpeas/web/directory/control/DirectorySessionController.java

unable to export users with no UserFull.

bug #12818:

---

core-api/src/main/java/org/silverpeas/core/util/StringUtil.java
core-api/src/test/java/org/silverpeas/core/util/StringUtilTest.java

Fix bug by taking into account the wildcard '_' in the Like statement in
StringUtil. For doing, the code of Like has been refactored and now the
expected text is scanned token per token and each token is processed
according its kind (a character or a wildcard) against a text.

Bug #12354 for 6.2.x

---

core-library/src/main/java/org/silverpeas/core/calendar/ical4j/ICal4JExporter.java
core-web/src/main/java/org/silverpeas/core/webapi/calendar/CalendarWebManager.java
core-web/src/main/java/org/silverpeas/core/webapi/calendar/ICalendarResource.java

Adding also the calendar name into ICAL file content.

Bug #12889: implementing @HEAD endpoints for ICal exports.

---

core-api/src/main/java/org/silverpeas/core/util/MemoizedSyncSupplier.java
core-configuration/src/main/config/properties/org/silverpeas/general.properties
core-configuration/src/main/config/properties/org/silverpeas/jcrmonitor/multilang/jcrMonitor.properties
core-configuration/src/main/config/properties/org/silverpeas/jcrmonitor/multilang/jcrMonitor_de.properties
core-configuration/src/main/config/properties/org/silverpeas/jcrmonitor/multilang/jcrMonitor_en.properties
core-configuration/src/main/config/properties/org/silverpeas/jcrmonitor/multilang/jcrMonitor_fr.properties
core-configuration/src/main/config/properties/org/silverpeas/jobManagerPeas/multilang/jobManagerPeasBundle.properties
core-configuration/src/main/config/properties/org/silverpeas/jobManagerPeas/multilang/jobManagerPeasBundle_de.properties
core-configuration/src/main/config/properties/org/silverpeas/jobManagerPeas/multilang/jobManagerPeasBundle_en.properties
core-configuration/src/main/config/properties/org/silverpeas/jobManagerPeas/multilang/jobManagerPeasBundle_fr.properties
core-configuration/src/main/config/properties/org/silverpeas/wbe/multilang/wbe.properties
core-configuration/src/main/config/properties/org/silverpeas/wbe/multilang/wbe_de.properties
core-configuration/src/main/config/properties/org/silverpeas/wbe/multilang/wbe_en.properties
core-configuration/src/main/config/resources/StringTemplates/core/admin/jcrmonitor/datastore_info_de.st
core-configuration/src/main/config/resources/StringTemplates/core/admin/jcrmonitor/datastore_info_en.st
core-configuration/src/main/config/resources/StringTemplates/core/admin/jcrmonitor/datastore_info_fr.st
core-library/src/main/java/org/silverpeas/core/persistence/jcr/JcrDatastoreManager.java
core-library/src/main/java/org/silverpeas/core/persistence/jcr/JcrDatastoreTaskMonitor.java
core-war/src/main/java/org/silverpeas/web/jcrmonitor/JcrMonitorWebController.java
core-war/src/main/java/org/silverpeas/web/jcrmonitor/JcrMonitorWebRequestContext.java
core-war/src/main/java/org/silverpeas/web/jobmanager/control/JobManagerPeasSessionController.java
core-war/src/main/webapp/WEB-INF/tags/silverpeas/admin/jcr/jcrDatastoreTaskContent.tag
core-war/src/main/webapp/WEB-INF/web.xml
core-war/src/main/webapp/jcrmonitor/jsp/jcrmonitor.jsp
core-web/src/main/java/org/silverpeas/core/web/look/LookSilverpeasV5Helper.java

The task execution can also be followed from the backoffice (MACRO MONITORING).

Feature #12910: Purge of JCR DataStore can now be done manually from backoffice.

---

core-library/src/main/java/org/silverpeas/core/admin/service/DefaultAdministration.java
core-war/src/main/webapp/jobDomainPeas/jsp/groupContent.jsp

Feature #11249: synchronized group are now managed as the standard ones.

---

core-library/src/main/java/org/silverpeas/core/index/indexing/model/FieldDescription.java
core-library/src/main/java/org/silverpeas/core/index/search/model/QueryDescription.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/782

Bug #13000: fixing component local search

---

core-library/src/main/java/org/silverpeas/core/contribution/content/form/PagesContext.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/AbstractFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/CheckBoxDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/DateFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/EmailFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/ListBoxFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/MapFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/RadioButtonDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/TextAreaFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/TextFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/TimeFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/UrlFieldDisplayer.java
core-library/src/main/java/org/silverpeas/core/contribution/content/form/form/XmlForm.java
core-war/src/main/webapp/templateDesigner/jsp/fieldDate.jsp
core-war/src/main/webapp/templateDesigner/jsp/fieldEmail.jsp
core-war/src/main/webapp/templateDesigner/jsp/fieldMap.jsp
core-war/src/main/webapp/templateDesigner/jsp/fieldMultivalues.jsp
core-war/src/main/webapp/templateDesigner/jsp/fieldText.jsp
core-war/src/main/webapp/templateDesigner/jsp/fieldTextarea.jsp
core-war/src/main/webapp/templateDesigner/jsp/fieldTime.jsp
core-war/src/main/webapp/templateDesigner/jsp/fieldURL.jsp
core-war/src/main/webapp/templateDesigner/jsp/template.jsp
core-war/src/main/webapp/util/styleSheets/silverpeas-main.css
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/DirectoryExtraFormTag.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/799

Bug #13261-6.4.x:  Improvement of the default value of a form field

---

core-war/src/main/webapp/ddwe/jsp/javaScript/silverpeas-ddwe-components.js
core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-event-occurrence-list-item.jsp
core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-event-occurrence-list.js
core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-event-occurrence-tip.jsp

Adding also the possibility to add occurrence events into basket selection from the next events view.

Bug #13382: adding explicitly a space at start of event end date into Drag & Drop Web Brwser Editor.

---

core-library/src/integration-test/java/org/silverpeas/core/admin/service/AdministrationSearchUserIT.java
core-library/src/integration-test/java/org/silverpeas/core/socialnetwork/mock/OrganizationControllerMock.java
core-library/src/main/java/org/silverpeas/core/admin/service/Administration.java
core-library/src/main/java/org/silverpeas/core/admin/service/DefaultAdministration.java
core-library/src/main/java/org/silverpeas/core/admin/service/DefaultOrganizationController.java
core-library/src/main/java/org/silverpeas/core/admin/service/OrganizationController.java
core-library/src/main/java/org/silverpeas/core/admin/user/dao/SqlUserSelectorByCriteriaBuilder.java
core-library/src/main/java/org/silverpeas/core/admin/user/model/AbstractSearchCriteria.java
core-library/src/main/java/org/silverpeas/core/admin/user/model/GroupsSearchCriteria.java
core-library/src/main/java/org/silverpeas/core/admin/user/model/SearchCriteria.java
core-library/src/main/java/org/silverpeas/core/admin/user/model/UserDetailsSearchCriteria.java
core-services/workflow/src/main/java/org/silverpeas/core/workflow/api/UserManager.java
core-services/workflow/src/main/java/org/silverpeas/core/workflow/engine/instance/ProcessInstanceImpl.java
core-services/workflow/src/main/java/org/silverpeas/core/workflow/engine/instance/WorkingUser.java
core-services/workflow/src/main/java/org/silverpeas/core/workflow/engine/user/UserManagerImpl.java
core-war/src/main/java/org/silverpeas/web/selection/control/SelectionPeasWrapperSessionController.java
core-war/src/main/java/org/silverpeas/web/selection/servlets/SelectionPeasWrapper.java
core-war/src/main/webapp/selection/jsp/userpanel.jsp
core-war/src/main/webapp/util/javaScript/silverpeas-user-group-list.js
core-war/src/main/webapp/util/javaScript/silverpeas-userZoom.js
core-war/src/main/webapp/util/javaScript/vuejs/components/silverpeas-user-group-select.js
core-war/src/main/webapp/util/styleSheets/silverpeas-main.css
core-web/src/main/java/org/silverpeas/core/web/selection/SelectionUsersGroups.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/JavascriptPluginInclusion.java
core-web/src/main/java/org/silverpeas/core/webapi/profile/UserProfileEntity.java
core-web/src/main/java/org/silverpeas/core/webapi/profile/UserProfilesSearchCriteriaBuilder.java
core-web/src/main/java/org/silverpeas/core/webapi/workflow/ReplacementResource.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/812

Feature 13497: it is now possible in a workflow to continue to replace an incumbent in a REMOVED state by a substitute.

---

core-war/src/main/webapp/util/styleSheets/silverpeas-main.css

Clean old agenda part css does not exist anymore. Replace gradient image by gradient css , and change annuaire CSS by Flex for more adaptation presentation.

Little clean Main CSS

---

core-war/src/main/java/org/silverpeas/web/directory/control/DirectorySessionController.java
core-war/src/main/java/org/silverpeas/web/directory/servlets/DirectoryRequestRouter.java
core-war/src/test/java/org/silverpeas/web/directory/control/DirectorySessionControllerTest.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/816

Feature #13552: adding new filtering possibility to directory feature.

---

core-services/comment/src/main/java/org/silverpeas/core/comment/dao/CommentDAO.java
core-services/comment/src/main/java/org/silverpeas/core/comment/dao/jdbc/JDBCCommentDAO.java
core-services/comment/src/main/java/org/silverpeas/core/comment/dao/jdbc/JDBCCommentRequester.java
core-services/comment/src/main/java/org/silverpeas/core/comment/service/CommentService.java
core-services/comment/src/main/java/org/silverpeas/core/comment/service/DefaultCommentService.java

Adding a new signature to comment services in order to get comment count of all resources of a specified type hosted by a component instance.
Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/849

Feature #13789: improving performances.

---

core-war/src/main/webapp/admin/jsp/silverpeas-navigation-part.jsp
core-war/src/main/webapp/pdcPeas/jsp/help.jsp
core-war/src/main/webapp/util/javaScript/silverpeas-layout.js
core-war/src/main/webapp/util/javaScript/silverpeas.js
core-war/src/main/webapp/util/styleSheets/silverpeas-main.css

* Adding new function sp.search.helpOn(...) in order to wire easily the search help
* modifying the existing help content in order to be displayed into a simple HTML container
Linked to PR https://github.com/Silverpeas/Silverpeas-Looks/pull/78

Feature #13795: adding help on global search input

---

core-library/src/main/java/org/silverpeas/core/security/authorization/ComponentInstanceSimpleDocumentAccessControlExtension.java
core-library/src/main/java/org/silverpeas/core/security/authorization/SimpleDocumentAccessController.java
core-war/src/main/java/org/silverpeas/web/usercalendar/security/authorization/UserCalendarInstanceAccessControlExtension.java
core-war/src/main/java/org/silverpeas/web/usercalendar/security/authorization/UserCalendarInstanceSimpleDocumentAccessControlExtension.java

Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/853

Bug #12281: checking simple document access control properly for attendees of event of personal user calendar

---

core-war/src/main/webapp/util/javaScript/jquery/slideShow/slideshow.css

Petite erreur CSS
Lié à feature #13962

Fix Bug #14119

---

core-api/src/main/java/org/silverpeas/core/thread/task/AbstractRequestTask.java
core-api/src/main/java/org/silverpeas/core/thread/task/RequestTaskManager.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/service/DefaultPublicationService.java
core-library/src/main/java/org/silverpeas/core/index/indexing/IndexEngineInitialize.java
core-library/src/main/java/org/silverpeas/core/index/indexing/IndexFileManager.java
core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexManager.java
core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexerTask.java
core-library/src/main/java/org/silverpeas/core/index/indexing/parser/ParserManager.java
core-library/src/main/java/org/silverpeas/core/notification/user/DefaultUserNotification.java
core-library/src/test/java/org/silverpeas/core/backgroundprocess/BackgroundProcessTaskTest.java
core-library/src/test/java/org/silverpeas/core/notification/sse/ServerEventDispatcherTaskLoadTest.java
core-services/sharing/src/integration-test/java/org/silverpeas/core/sharing/services/JpaSharingTicketServiceIT.java

Fix the bug by setting the index entry language with the one of the publication from which the index entry is built.
Improve some codes according to the feedback of the IntelliJ and SonarLint static code anlysis.

Bug #13689

---

core-library/src/main/java/org/silverpeas/core/contribution/publication/model/PublicationDetail.java
core-library/src/main/java/org/silverpeas/core/contribution/publication/service/DefaultPublicationService.java

In DefaultPublicationService, an index is created for a give publication only if this same publication is indexable.
Related to PR https://github.com/Silverpeas/Silverpeas-Components/pull/855

Bug #13512

---

core-rs/src/main/java/org/silverpeas/core/web/http/HttpRequest.java
core-web/src/main/java/org/silverpeas/core/web/filter/MassiveWebSecurityFilter.java
core-web/src/main/java/org/silverpeas/core/webapi/calendar/CalendarWebManager.java

Fix vulnerability  by introducing injection checking in entity embodied within incoming HTTP requests.
The checking is performed only if the request embodies a web entity encoded in a supported content type, id est in JSON or in XML.

Bug #14176 Fix vuln

---

core-war/src/main/java/org/silverpeas/web/notificationuser/servlets/UserNotificationRequestRouter.java
core-war/src/main/webapp/WEB-INF/tags/silverpeas/util/attachmentDragAndDrop.tag
core-war/src/main/webapp/WEB-INF/tags/silverpeas/util/commonDragAndDrop.tag
core-war/src/main/webapp/attachment/jsp/displayAttachedFiles.jsp
core-war/src/main/webapp/portlets/jsp/lastPublications/portlet.jsp
core-war/src/main/webapp/portlets/jsp/myLastPubliRead/portlet.jsp
core-war/src/main/webapp/socialNetwork/jsp/js/newsfeed.js
core-war/src/main/webapp/util/javaScript/silverpeas-ddUpload.js
core-war/src/main/webapp/util/javaScript/silverpeas-fileUpload.js
core-war/src/main/webapp/util/javaScript/silverpeas.js
core-web/src/main/java/org/silverpeas/core/web/attachment/tag/SimpleDocumentContextualMenu.java
core-web/src/main/java/org/silverpeas/core/webapi/attachment/SimpleDocumentResource.java
core-web/src/main/java/org/silverpeas/core/webapi/attachment/SimpleDocumentResourceCreator.java

In several very peculiar locations in the code, both in JS and in Java, the filename, description or title of an attachment (or of a publication), aren't correctly escaped for HTML rendering. Fix those omissions.
In order the bug to be fixed, the following PR require to be taken into account with this one:
- https://github.com/Silverpeas/Silverpeas-Components/pull/866
- https://github.com/Silverpeas/Silverpeas-Looks/pull/89

Bug #14478

---

core-war/src/main/java/org/silverpeas/web/socialnetwork/myprofil/servlets/GoToMyProfile.java
core-war/src/main/java/org/silverpeas/web/socialnetwork/myprofil/servlets/JSONServlet.java
core-war/src/main/java/org/silverpeas/web/socialnetwork/myprofil/servlets/MyProfilRequestRouter.java
core-war/src/main/java/org/silverpeas/web/socialnetwork/myprofil/servlets/MyProfileRoutes.java
core-war/src/main/java/org/silverpeas/web/socialnetwork/myprofil/servlets/SocialNetworkHelper.java
core-war/src/main/webapp/socialNetwork/jsp/myProfil/myProfile.jsp
core-war/src/main/webapp/socialNetwork/jsp/myProfil/myProfileTabIdentity.jsp
core-war/src/main/webapp/socialNetwork/jsp/myProfil/myProfileTabInvitations.jsp
core-war/src/main/webapp/socialNetwork/jsp/myProfil/myProfileTabSettings.jsp
core-war/src/main/webapp/socialNetwork/jsp/myProfil/myProfileTabWall.jsp
core-war/src/main/webapp/util/styleSheets/silverpeas-main.css

Fix the vulnerability by using now the POST Ajax request to update the status. The servlet accepts only HTTP POST method. The data are sent foth and back in JSON.

Bug #14505

---

core-api/src/main/java/org/silverpeas/core/notification/message/AbstractMessage.java
core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-event-form-main.jsp
core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-event-occurrence-list.js
core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-event-view.js
core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-management.js
core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar.js
core-war/src/main/webapp/util/javaScript/angularjs/silverpeas-adapters.js
core-web/src/integration-test/java/org/silverpeas/core/webapi/selection/SelectionBasketItemDeletingIT.java
core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/browsebars/BrowseBarElement.java

Fix the vulnerability by ensuring the data of the events/event occurrences are correctly encoded for the HTML rendering.
Ensures also notification messages in Silverpeas are also correctly encoded for their HTML rendering.

Bug #14475

---

core-library/src/main/java/org/silverpeas/core/socialnetwork/invitation/Invitation.java
core-library/src/main/java/org/silverpeas/core/socialnetwork/invitation/InvitationDao.java
core-library/src/main/java/org/silverpeas/core/socialnetwork/invitation/InvitationService.java
core-library/src/main/java/org/silverpeas/core/socialnetwork/relationship/RelationShipDao.java
core-web/src/main/java/org/silverpeas/core/webapi/socialnetwork/invitation/InvitationResource.java

Fix the vulnerability by checking the user accessing an invitation is related by it (he's one of the user related by the invitation)

Bug #14544

---

core-war/src/main/webapp/pdcSubscriptionPeas/jsp/subscription.jsp
core-war/src/main/webapp/pdcSubscriptionPeas/jsp/subscriptionList.jsp
core-war/src/main/webapp/pdcSubscriptionPeas/jsp/viewSubscriptionsOfCategory.jsp

Fix vulnerability by encoding in HTML titles and labels of subscriptions

Bug #14566

---

core-configuration/src/main/config/data/web/weblib.war/ckeditor/identitycard/sample_template.html
core-war/src/main/webapp/wysiwyg/jsp/ckeditor/plugins/identitycard/dialogs/identitycard.js
core-war/src/main/webapp/wysiwyg/jsp/ckeditor/plugins/identitycard/plugin.js
core-web/src/main/java/org/silverpeas/core/webapi/profile/UserProfileExtendedEntity.java

Fix the identity card's template in which the reference to the email field of the javascript user entity wasn't correctly named.

Bug #14588

---

core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/layout/BodyPartLayoutTag.java
core-web/src/main/resources/META-INF/viewGenerator.tld

Add the onUnload javascript event to the BodyPart tag.
This PR is for the PR https://github.com/Silverpeas/Silverpeas-Components/pull/882 which resolves the bug

Bug #14481

---

core-war/src/main/webapp/util/styleSheets/silverpeas-calendar.css
core-war/src/main/webapp/util/styleSheets/silverpeas-main.css

Define variable CSS for general use
Linked with 2 others PRs

Clean CSS and variable definition

---

core-api/src/main/java/org/silverpeas/core/admin/user/model/SilverpeasRole.java
core-library/src/main/java/org/silverpeas/core/admin/component/model/ComponentInst.java
core-library/src/main/java/org/silverpeas/core/admin/service/AdminController.java
core-library/src/main/java/org/silverpeas/core/admin/space/SpaceProfileInstManager.java
core-library/src/main/java/org/silverpeas/core/admin/space/notification/SpaceProfileInstEvent.java
core-library/src/main/java/org/silverpeas/core/admin/space/notification/SpaceProfileInstEventNotifier.java
core-library/src/main/java/org/silverpeas/core/admin/user/ProfileInstManager.java
core-library/src/main/java/org/silverpeas/core/admin/user/notification/ProfileInstEvent.java
core-library/src/main/java/org/silverpeas/core/admin/user/notification/ProfileInstEventNotifier.java
core-war/src/main/webapp/jobDomainPeas/jsp/userContent.jsp

This PR is related to https://github.com/Silverpeas/Silverpeas-Components/pull/893
Provide another solution to the fix of the bug, based upon the system event notification mechanism.
Add and use the notification of event about actions performed against access right profile instances.

Bug #14595

---

core-rs/src/main/java/org/silverpeas/core/web/token/SynchronizerTokenService.java
core-war/src/main/java/org/silverpeas/web/todo/servlets/TodoRequestRouter.java
core-war/src/main/webapp/todo/jsp/todoEdit.jsp
core-web/src/main/java/org/silverpeas/core/web/filter/exception/WebSecurityException.java

The pb is the query part of the URI of HTTP GET requests isn't taken when checking for attempt to perform a CRUD operation on a resource in Silverpeas. Now all parts of the query is checked.
Ensure also to avoid regexp flooding.

Bug #14836

---

core-war/src/main/webapp/wysiwyg/jsp/htmlEditor.jsp

Whatever a rich content of a contribution is added or updated, check the content cache for text to decide if a notification about contribution modification has to be triggered (in the case such notif is supported).
Related to PR https://github.com/Silverpeas/Silverpeas-Components/pull/902

Bug #14770

---

core-web/src/main/java/org/silverpeas/core/web/attachment/tag/SimpleDocumentContextualMenu.java

Fix bug by using the more adequant OWASP Encode method.

Bug #14752
