Silverpeas/Silverpeas-Core

- ejb-core/formtemplate/src/main/java/com/silverpeas/workflow/engine/instance/ProcessInstanceImpl.java
Fix the bug with the solution provided by Etienne in redmine (https://tracker.silverpeas.org/issues/5992)
> Fix a bug about the unlocking of a process instance in a workflow

- ejb-core/comment/src/main/java/com/silverpeas/comment/dao/jdbc/JDBCCommentRequester.java
- lib-core/src/main/java/com/stratelia/webactiv/beans/admin/dao/ComponentDAO.java
- the public component instance identifiers were not filtered according to a specified and defined component name (but unfortunately, this point can not functionnally be verified because it will just increase Silverpeas performances)
- sometimes a comment search is filtered on component instance identifiers that the user can access. When no component instance identifier was accessible to the user, the SQL query built in order to get comments was malformed
> Bug #6677, fixing two problems.

- lib-core/src/main/java/com/stratelia/silverpeas/notificationManager/NotificationSender.java
- lib-core/src/main/java/com/stratelia/webactiv/beans/admin/Admin.java
- lib-core/src/main/java/com/stratelia/webactiv/beans/admin/Group.java
- lib-core/src/main/java/com/stratelia/webactiv/beans/admin/GroupManager.java
- lib-core/src/main/java/com/stratelia/webactiv/beans/admin/dao/UserDAO.java
- lib-core/src/main/java/org/silverpeas/core/admin/OrganisationController.java
- war-core/src/main/webapp/jobDomainPeas/jsp/domainContent.jsp
- war-core/src/main/webapp/jobDomainPeas/jsp/groupContent.jsp
- web-core/src/main/java/com/silverpeas/jobDomainPeas/control/JobDomainPeasSessionController.java
- web-core/src/main/java/com/silverpeas/profile/web/UserGroupProfileEntity.java
- web-core/src/test/java/com/silverpeas/profile/web/UserProfileTestResources.java
The use of the Group#setNbUsers(int) isn't consistent among the code. Some codes use it to set the direct number of users in the group as expected (in Admin) whereas others use it to set the total number of users in the group (by taking into account the subgroups). This part was cleaned and in order to avoid this misuse the Group#setNbUsers(int) and Group#setTotalNbUsers(int) are now removed.
Up to now, the method Group#getNbUsers() computes the number of direct users from the size of the array of users' identifiers that was set to the group by the GroupManager (it is always set when returning one or more groups), so there is no need to let external code to set the direct user count.
In the other side, up to now, the method Group#getTotalNbUsers() computes recursively the number of users …
> Fix bug 6937

- lib-core/src/main/java/com/stratelia/silverpeas/notificationManager/NotificationSender.java
- lib-core/src/main/java/com/stratelia/webactiv/beans/admin/Admin.java
- lib-core/src/main/java/com/stratelia/webactiv/beans/admin/Group.java
- lib-core/src/main/java/com/stratelia/webactiv/beans/admin/GroupManager.java
- lib-core/src/main/java/com/stratelia/webactiv/beans/admin/UserDetailsSearchCriteria.java
- lib-core/src/main/java/com/stratelia/webactiv/beans/admin/dao/UserDAO.java
- lib-core/src/main/java/org/silverpeas/core/admin/OrganisationController.java
- lib-core/src/test/java/com/stratelia/silverpeas/notificationManager/NotificationMetaDataTest.java
- war-core/src/main/webapp/jobDomainPeas/jsp/domainContent.jsp
- war-core/src/main/webapp/jobDomainPeas/jsp/groupContent.jsp
- war-core/src/main/webapp/util/javaScript/angularjs/services/silverpeas-profile.js
- web-core/src/main/java/com/silverpeas/jobDomainPeas/control/JobDomainPeasSessionController.java
- web-core/src/main/java/com/silverpeas/profile/web/UserGroupProfileEntity.java
- web-core/src/test/java/com/silverpeas/profile/web/UserProfileTestResources.java
The total number of users in a group counts users that are in several subgroups only once. This count is now centralized into one method Admin#getAllSubUsersNumber(groupId) that invokes the GroupManager#groupManager.getTotalUserCountInGroup(domainId, groupId) method when the groupId is specified (otherwise it invokes the UserManager#getUserNumber(domainDriverManager) method). In the case only some users whose the account isn't in a given state must be taken into account, the method Admin#searchUsers(UserDetailsSearchCriteria) should be used instead. The groups that are returned by Admin#searchGroups(GroupsSearchCriteria) take already into account of this contrain for the total users number. In the other side, the number of direct users in a group is directly computed from the size of the …
> Fix bug 6937 for 5.15

- config-core/src/main/config/properties/org/silverpeas/notificationManager/settings/notificationManagerSettings.properties
- lib-core/src/main/java/com/silverpeas/notification/builder/AbstractUserNotificationBuilder.java
- lib-core/src/main/java/com/silverpeas/notification/builder/UserSubscriptionNotificationBehavior.java
- lib-core/src/main/java/com/silverpeas/notification/jms/SilverpeasMessageListener.java
- lib-core/src/main/java/com/stratelia/silverpeas/notificationManager/NotificationManagerSettings.java
- lib-core/src/main/java/com/stratelia/silverpeas/notificationManager/NotificationMetaData.java
- lib-core/src/test/java/com/stratelia/silverpeas/notificationManager/NotificationMetaDataTest.java
- war-core/src/main/java/com/stratelia/silverpeas/notificationUser/control/NotificationUserSessionController.java
Adding a new parameter that permits to enable/disable this removing.
So, roll-backing the treatment of notification sending to previous version about the remove of the sender from the receivers (see REDMINE #6073).
This commit is only compatible with 5.15.x version and the next one. Do not report to previous one.
> Feature #6519: the sender is now removed from the receivers only if the notification concerns a subscription.

- lib-core/src/main/java/org/silverpeas/attachment/SimpleDocumentService.java
- lib-core/src/main/java/org/silverpeas/attachment/repository/DocumentRepository.java
- lib-core/src/test/java/org/silverpeas/attachment/repository/DocumentRepositoryTest.java
- lib-core/src/test/java/org/silverpeas/attachment/repository/HistorisedDocumentRepositoryTest.java
- war-core/src/main/java/org/silverpeas/attachment/web/AjaxServlet.java
- war-core/src/main/webapp/attachment/jsp/displayAttachedFiles.jsp
https://tracker.silverpeas.org/issues/7216
Do not report this PR into Silverpeas V6.
> Fixing #7216 : the last modified data of an attachment is no more updated on lock and unlock with discard operations.

- lib-core/src/main/java/com/silverpeas/form/displayers/WysiwygFCKFieldDisplayer.java
- lib-core/src/main/java/com/silverpeas/form/form/XmlForm.java
- lib-core/src/main/java/com/silverpeas/form/record/GenericRecordSet.java
- lib-core/src/main/java/com/silverpeas/form/record/GenericRecordSetManager.java
Fallback on all managed languages when getting a form content (same behavior as WYSIWYG content)
Do not omit to check out corresponding PR on Silverpeas-Components...
> [i18n] Fixing bug 7226

- lib-core/src/main/java/com/stratelia/silverpeas/domains/ldapdriver/LDAPUtility.java
Always throwing LDAPException (except SIZE_LIMIT_EXCEEDED and TIME_LIMIT_EXCEEDED which are managed cases)...
> [LDAP Synchro] Fixing bug 7729

- lib-core/src/main/java/org/silverpeas/wysiwyg/control/WysiwygController.java
- lib-core/src/main/java/org/silverpeas/wysiwyg/control/WysiwygManager.java
- web-core/src/main/java/com/silverpeas/importExport/control/GEDImportExport.java
Fix is in WysiwygManager.java. The callback mechanism was wrongly invoked.
At this occasion, signature of involved method has been changed by deleting an useless parameter.
Do not omit to check out PR on Silverpeas-Components...
> [GED] Fixing bug 8291

- core-api/src/main/java/org/silverpeas/core/util/DateUtil.java
- core-configuration/src/main/config/properties/org/silverpeas/pdcPeas/multilang/pdcBundle.properties
- core-configuration/src/main/config/properties/org/silverpeas/pdcPeas/multilang/pdcBundle_de.properties
- core-configuration/src/main/config/properties/org/silverpeas/pdcPeas/multilang/pdcBundle_en.properties
- core-configuration/src/main/config/properties/org/silverpeas/pdcPeas/multilang/pdcBundle_fr.properties
- core-library/src/main/java/org/silverpeas/core/contribution/content/form/record/GenericRecordSet.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/DateFormatter.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/model/FieldDescription.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/model/FullIndexEntry.java
- core-library/src/main/java/org/silverpeas/core/index/search/model/IndexSearcher.java
- core-war/src/main/java/org/silverpeas/web/pdc/control/PdcSearchSessionController.java
- core-war/src/main/java/org/silverpeas/web/pdc/servlets/PdcSearchRequestRouter.java
- core-war/src/main/java/org/silverpeas/web/pdc/vo/FacetOnDates.java
- core-war/src/main/java/org/silverpeas/web/pdc/vo/ResultFilterVO.java
- core-war/src/main/java/org/silverpeas/web/pdc/vo/ResultGroupFilter.java
- core-war/src/main/webapp/pdcPeas/jsp/globalResult.jsp
- core-war/src/main/webapp/templateDesigner/jsp/includeParamsField.jsp
- core-web/src/main/java/org/silverpeas/core/webapi/search/ResultEntity.java
- core-web/src/main/java/org/silverpeas/core/webapi/search/SearchResource.java
This PR is a duplicate of [PR #786](https://github.com/Silverpeas/Silverpeas-Core/pull/786) in order to have a control on it for fixing any problems coming from the build.
Updating feature #3840, now :
- Repeatable form fields are well indexed (all values and not only the first one),
- REST API allows to querying on desired form fields,
- Results contain data from stored fields,
- Form field of type 'date' can be used as facet.
Closing partially feature #8172. First version of 'Last update' facet is here (one entry per year for the moment).
> [Search] updating feature 3840 and closing partially feature 8172

- core-library/src/main/java/org/silverpeas/core/admin/domain/model/Domain.java
- core-library/src/main/java/org/silverpeas/core/admin/service/Admin.java
- core-war/src/main/java/org/silverpeas/web/jobdomain/control/JobDomainPeasSessionController.java
- core-war/src/main/webapp/jobDomainPeas/jsp/domainContent.jsp
- core-war/src/main/webapp/jobStartPagePeas/jsp/spaceLook.jsp
- core-war/src/main/webapp/socialNetwork/jsp/myProfil/myProfileTabSettings.jsp
- core-web/src/main/java/org/silverpeas/core/web/authentication/SilverpeasSessionOpener.java
- core-web/src/main/java/org/silverpeas/core/web/look/LookSilverpeasV5Helper.java
- core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/GraphicElementFactory.java
See https://tracker.silverpeas.org/issues/3114 for further information
> Looks per domain

- core-configuration/src/main/config/properties/org/silverpeas/util/logging/silverpeasSsoLogging.properties
- core-war/src/main/java/org/silverpeas/web/token/SessionSynchronizerTokenValidator.java
- core-war/src/main/webapp/WEB-INF/web.xml
- core-war/src/main/webapp/jobManagerPeas/jsp/topBarManager.jsp
- core-war/src/main/webapp/util/javaScript/silverpeas-lang.js
- core-war/src/main/webapp/util/javaScript/silverpeas-user-session.js
- core-web/src/main/java/org/silverpeas/core/web/authentication/AuthenticationParameters.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/AuthenticationServlet.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/LoginServlet.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/LogoutServlet.java
- core-web/src/main/java/org/silverpeas/core/web/sso/SilverpeasSsoHttpRequest.java
- core-web/src/main/java/org/silverpeas/core/web/sso/SilverpeasSsoHttpServlet.java
- core-web/src/main/java/org/silverpeas/core/web/sso/SilverpeasSsoPrincipal.java
On "/sso" uri, Silverpeas is checking the user principal of the current request. If it is a SilverpeasSsoPrincipal one, then the authentication is peformed automatically with the data provided by the principal.
By this way, additional Silverpeas module (like silverpeas-sso-azure) in charge of performing user authentications by delegating it to authorities servers (like the one of Azure AD) can easily supply the PRINCIPAL to Silverpeas authentication.
> Handling a new way of SSO user authentication.

- core-api/src/main/java/org/silverpeas/core/util/logging/SilverLoggerProvider.java
- core-library/src/main/java/org/silverpeas/core/util/logging/sys/SysLogger.java
- core-library/src/main/java/org/silverpeas/core/util/logging/sys/SysLoggerFactory.java
- core-library/src/test/java/org/silverpeas/core/util/logging/sys/SysLoggerFactoryTest.java
- core-library/src/test/java/org/silverpeas/core/util/logging/sys/SysLoggerTest.java
The cache of the loggers is now replaced by a WeakHashMap that is more efficient in its management of the WeakReference that our own custom mechanism
> Fix the bug #9552

- lib-core/src/main/java/org/silverpeas/attachment/repository/DocumentConverter.java
- war-core/src/main/java/org/silverpeas/attachment/web/VersioningRequestRouter.java
- war-core/src/main/java/org/silverpeas/attachment/web/VersioningSessionController.java
- war-core/src/main/webapp/attachment/jsp/publicVersions.jsp
- fixing the attachment version history display which was loosing the content language set on parent page
- adding possibility to sort on version column
- applying popup display behavior
- fixing a problem around the copy of attachments of a publication
Linked to PR: https://github.com/Silverpeas/Silverpeas-Components/pull/570
> Bug #9601 & #9612

- core-library/src/integration-test/java/org/silverpeas/core/contribution/attachment/repository/HistorisedDocumentRepositoryIT.java
- core-library/src/main/java/org/silverpeas/core/contribution/attachment/repository/DocumentConverter.java
- core-war/src/main/java/org/silverpeas/web/attachment/VersioningSessionController.java
- core-war/src/main/webapp/attachment/jsp/publicVersions.jsp
- fixing the attachment version history display which was loosing the content language set on parent page
- adding possibility to sort on version column
- applying popup display behavior
- fixing a problem around the copy of attachments of a publication
Linked to PR: https://github.com/Silverpeas/Silverpeas-Components/pull/572
> Bug #9601 & #9612:

- core-api/src/main/java/org/silverpeas/core/util/ResourceLocator.java
Now the bundle base name in Silverpeas can be either "org.silverpeas" or "com.silverpeas.customers".
Increase the log level from ERROR to WARN when a bundle name doesn't start by
one of the above base name.
> Fix the bug 9650

- core-library/src/main/java/org/silverpeas/core/util/DocumentInfo.java
- core-library/src/main/java/org/silverpeas/core/util/PdfUtil.java
- core-services/viewer/src/integration-test/java/org/silverpeas/core/viewer/service/PreviewServiceWithoutSwfrenderIT.java
- core-services/viewer/src/main/java/org/silverpeas/core/viewer/flexpaper/TemporaryFlexPaperView.java
- core-services/viewer/src/main/java/org/silverpeas/core/viewer/model/TemporaryPdfView.java
- core-services/viewer/src/main/java/org/silverpeas/core/viewer/service/DefaultPreviewService.java
- core-services/viewer/src/main/java/org/silverpeas/core/viewer/service/DefaultViewService.java
- core-services/viewer/src/main/java/org/silverpeas/core/viewer/service/SwfToolManager.java
- core-services/viewer/src/main/java/org/silverpeas/core/viewer/util/SwfUtil.java
- core-services/viewer/src/test/java/org/silverpeas/core/viewer/util/SwfUtilTest.java
- getting document info from iText instead of using external tool which is difficult to handle with on an environment side
- replacing pdf2swf calls by other tool calls (but keeping yet the tool for special requirements)
- fixing sonar feedback
> Feature #9387: avoiding to use pdf2swf

- core-library/src/integration-test/java/org/silverpeas/core/process/management/interceptor/DefaultEjbService.java
- core-library/src/integration-test/java/org/silverpeas/core/process/management/interceptor/DefaultSimpleService.java
- core-library/src/integration-test/java/org/silverpeas/core/process/management/interceptor/SimulationActionInterceptorIT.java
- core-library/src/integration-test/resources/org/silverpeas/util/logging/processLogging.properties
- core-library/src/main/java/org/silverpeas/core/node/service/DefaultNodeService.java
- core-library/src/main/java/org/silverpeas/core/process/annotation/SimulationActionProcessAnnotationInterceptor.java
- core-services/importExport/src/main/java/org/silverpeas/core/importexport/control/GEDImportExport.java
- core-services/workflow/src/main/java/org/silverpeas/core/workflow/engine/WorkflowTools.java
In SendInKmelia: the creation of the node(s) into which the publication will
be put are now performed into a new transaction so that if the creation fails
it doesn't rollback all the process and once the creation is done, the nodes
are accessed out of the transaction further in the task execution.
Don't forget to merge after https://github.com/Silverpeas/Silverpeas-Components/pull/635
> Fix bug #10358

- core-api/src/main/java/org/silverpeas/core/notification/user/NotificationContext.java
- core-library/src/integration-test/java/org/silverpeas/core/notification/system/asynchronous/MassiveAsynchronousNotificationIT.java
- core-library/src/test/java/org/silverpeas/core/process/io/file/TestFileHandler.java
- core-war/src/main/java/org/silverpeas/web/notificationuser/servlets/UserNotificationRequestRouter.java
- core-war/src/main/java/org/silverpeas/web/selection/control/SelectionPeasWrapperSessionController.java
- core-war/src/main/java/org/silverpeas/web/selection/servlets/SelectionPeasWrapper.java
- core-war/src/main/webapp/WEB-INF/tags/silverpeas/util/selectUsersAndGroups.tag
- core-war/src/main/webapp/selection/jsp/userpanel.jsp
- core-war/src/main/webapp/userNotification/jsp/notificationSender.jsp
- core-war/src/main/webapp/util/javaScript/angularjs/services/silverpeas-profile.js
- core-war/src/main/webapp/util/javaScript/silverpeas-user-group-list.js
- core-war/src/main/webapp/util/javaScript/silverpeas-userZoom.js
- core-web/src/main/java/org/silverpeas/core/web/selection/SelectionUsersGroups.java
- core-web/src/main/java/org/silverpeas/core/webapi/profile/UserProfileResource.java
In the user notification transverse module, the receivers that can be selected
can be now filtered also by the resource they can access and for which the
notification is sent. Such resource can be for example a node that is a generic
way to represent a category or a topic to categorize the contributions.
Replace Thread.sleep by Awaitility in MassiveAsynchronousNotificationIT
Don't forget to merge after https://github.com/Silverpeas/Silverpeas-Components/pull/658
> Bug #10857

- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/DefaultJdbcSqlExecutor.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlBigDecimalParamSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlBigIntegerParamSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlBinaryParamSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlBooleanParamSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlDateParamSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlDateTimeParamSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlEnumParamSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlIntegerParamSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlLongParamSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlStatementParameterSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlTemporalParamSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlTextSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/SqlTypedParameterSetter.java
- core-api/src/main/java/org/silverpeas/core/persistence/jdbc/sql/setters/package-info.java
- core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/pagination/AbstractPagination.java
Fix the bug 10993
Don't forget to merge also the PR https://github.com/Silverpeas/Silverpeas-Components/pull/664
This is this PR that fixes the bug.
Split the setting of the SQL parameters in a PreparedStatement into several
setter objects, each of them dedicated to set a specific parameter type.
This is to avoid the use of multiple if-conditions and it allow to add more
easily an additional setter without having to modify the implementation of the
JdbcSqlExecutor interface.
Improve the setter of SQL date by taking explicitly into account the type of the
parameter value is of type java.sql.Date.
> Bug #10993

- core-war/src/main/java/org/silverpeas/web/servlets/GoToFile.java
- core-war/src/main/webapp/util/javaScript/silverpeas-view.js
- core-web/src/main/java/org/silverpeas/core/webapi/viewer/DocumentViewEntity.java
The Silverpeas's PDF viewer is now provided instead of the one of the WEB browser.
As it is encapsulated into a safe iframe, there is no more side effect with the iframe of the Silverpeas's layout.
> Bug #11039: making the display of PDF attached files (via a permalinkURL) possible without breaking out the Silverpeas's navigation.

- core-library/src/main/java/org/silverpeas/core/contribution/attachment/model/SimpleDocument.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/PublicationCriteria.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/PublicationDAO.java
- core-library/src/main/java/org/silverpeas/core/security/authorization/PublicationAccessController.java
- core-library/src/test/java/org/silverpeas/core/contribution/attachment/model/SimpleDocumentTest.java
- core-library/src/test/java/org/silverpeas/core/security/authorization/TestPublicationAccessController.java
- core-war/src/main/java/org/silverpeas/web/attachment/VersioningRequestRouter.java
- core-war/src/main/java/org/silverpeas/web/attachment/VersioningSessionController.java
- core-war/src/main/webapp/attachment/jsp/displayAttachedFiles.jsp
- core-war/src/main/webapp/attachment/jsp/publicVersions.jsp
- core-web/src/main/java/org/silverpeas/core/web/attachment/tag/SimpleDocumentContextualMenu.java
- core-web/src/main/resources/META-INF/contextMenu.tld
The computing of alias URL has been deleted and attachment URL is now always provided, the document displayed as an alias or not.
Fixing also a problem on an other subject. The lastest publication displayed on Silverpeas's homepage (and the homepage of the GED too). Now the ordering is taking into account rightly the visibility period against the update date of publications.
Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/674
> Bug #11118: removing AliasFileServer servlet which was supplying wrongly the documents.

- core-library/src/main/java/org/silverpeas/core/admin/service/Admin.java
- core-library/src/main/java/org/silverpeas/core/admin/user/GroupManager.java
- core-library/src/main/java/org/silverpeas/core/admin/user/UserManager.java
- core-library/src/main/java/org/silverpeas/core/admin/user/dao/GroupSearchCriteriaForDAO.java
- core-library/src/main/java/org/silverpeas/core/admin/user/dao/UserSearchCriteriaForDAO.java
- core-library/src/main/java/org/silverpeas/core/admin/user/model/SearchCriteria.java
- core-library/src/main/java/org/silverpeas/core/admin/user/model/UserDetail.java
- core-library/src/main/java/org/silverpeas/core/admin/user/model/UserDetailsSearchCriteria.java
- core-library/src/main/java/org/silverpeas/core/security/authorization/ComponentAccessController.java
- core-war/src/main/webapp/selection/jsp/userpanel.jsp
- core-war/src/main/webapp/subscription/jsp/subscriptionpanel.jsp
- core-war/src/main/webapp/util/javaScript/silverpeas-user-group-list.js
- core-web/src/main/java/org/silverpeas/core/webapi/admin/scim/ScimUserAdminService.java
- core-web/src/main/java/org/silverpeas/core/webapi/profile/UserProfileResource.java
- core-web/src/main/java/org/silverpeas/core/webapi/profile/UserProfilesSearchCriteriaBuilder.java
Now, by default, the search of users by criteria doesn't exclude the removed
ones. A removed user is a user that is a deletion awaiting; its account isn't
then deleted and it can be restored later with the right access profiles.
It is then now required to explicitly exclude the removed users in the search.
By doing so, no more errors are thrown when we are looking for users with among
them some whose account in Silverpeas is removed; this is the case with the
user subscriptions for example.
Don't forget to merge also PR https://github.com/Silverpeas/Silverpeas-Components/pull/675
> Bug #11135

- core-library/src/main/java/org/silverpeas/core/contribution/attachment/AttachmentService.java
- core-library/src/main/java/org/silverpeas/core/contribution/attachment/SimpleDocumentService.java
- core-services/importExport/src/main/java/org/silverpeas/core/importexport/attachment/AttachmentImportExport.java
- core-web/src/main/java/org/silverpeas/core/webapi/attachment/SimpleDocumentResourceCreator.java
- trying to fix a new case of combined character encoding in filename of file uploaded from apple computers (workflow case). The normalization of the filename (which consists to encode all each combined character into a single character) is now applied into creation and modification features provided by simple document service API.
- fixing case of import engine
- fixing SonarQube feedback
> Bug #11267: fixing new cases of combined characters to normalize into single characters before saving data into JCR.

- core-configuration/src/main/config/properties/org/silverpeas/converter/openoffice.properties
- core-configuration/src/main/config/properties/org/silverpeas/util/attachment/mime_types.properties
- core-library/src/main/java/org/silverpeas/core/contribution/converter/DocumentFormatConverterProvider.java
- core-library/src/main/java/org/silverpeas/core/contribution/converter/ToPDFConverter.java
- core-library/src/main/java/org/silverpeas/core/contribution/converter/openoffice/OpenOfficeService.java
- core-library/src/main/java/org/silverpeas/core/contribution/converter/openoffice/OpenOfficeToPDFConverter.java
- core-library/src/main/java/org/silverpeas/core/util/MimeTypes.java
- core-library/src/test/java/org/silverpeas/core/util/MimeTypeRegistryTest.java
- core-library/src/test/resources/org/silverpeas/util/attachment/mime_types.properties
- core-services/viewer/src/main/java/org/silverpeas/core/viewer/service/DefaultPreviewService.java
- core-services/viewer/src/main/java/org/silverpeas/core/viewer/service/DefaultViewService.java
- adding a new mechanism of mime-type registry which can be used by several services. Each service using it is able to define its own mime-type registry. Here, the office document to PDF converter defines now its own registry of handled mime-types and the converter itself is able to indicates to other services (as viewer or previewer ones) if a file is supported or not
- making that the viewer and previewer services depends to the office document to PDF converter in order to verify if a file is supported or not
- taking into account template office documents by default
> Bug #7598: making template documents compatible with viewer and previewer.

- core-api/src/main/java/org/silverpeas/core/template/SilverpeasStringTemplate.java
- core-api/src/main/java/org/silverpeas/core/template/SilverpeasTemplate.java
- core-library/src/main/java/org/silverpeas/core/notification/user/delayed/delegate/DelayedNotificationDelegate.java
When a String is produced with StringTemplate API from a set of template files (not a single file), the customization was not effective when just a few (not all) of template files were overridden.
The detection of the template file directory (the one of the product or the one of customizations) was not rightly done because the customization needs all template files customized and not just a few.
A modification has been done in order to permits to customize just the needed template files. Now, when a custom folder exists and if it has been requested to StringTemplate API, the template files from product and the customized are merged into a new folder and the template files taken into account from string producing come from this new folder.
The new folder is called …
> Bug #11365: making complex string templates customizable.

- core-api/src/main/java/org/silverpeas/core/util/StringUtil.java
- core-library/src/main/java/org/silverpeas/core/calendar/notification/AttendeeNotificationBuilder.java
- core-library/src/main/java/org/silverpeas/core/calendar/notification/CalendarEventUserNotificationReminder.java
- core-library/src/main/java/org/silverpeas/core/socialnetwork/provider/SocialEventProvider.java
- core-war/pom.xml
- core-war/src/integration-test/java/org/silverpeas/web/test/WarBuilder4WarCore.java
- core-war/src/integration-test/java/org/silverpeas/web/usercalendar/socialnetwork/DefaultUserCalendarEventOccurrenceSocialProviderIT.java
- core-war/src/integration-test/resources/META-INF/services/test-org.silverpeas.core.util.logging.SilverLoggerFactory
- core-war/src/integration-test/resources/maven.properties
- core-war/src/integration-test/resources/org/silverpeas/web/usercalendar/socialnetwork/calendar-dataset.sql
- core-war/src/integration-test/resources/org/silverpeas/web/usercalendar/socialnetwork/create-database.sql
- core-war/src/integration-test/resources/xmlcomponents/personals/userCalendar.xml
- core-war/src/main/java/org/silverpeas/web/socialnetwork/newsfeed/servlets/NewsFeedJSONServlet.java
- core-war/src/main/java/org/silverpeas/web/usercalendar/services/UserCalendarWebManager.java
- core-war/src/main/java/org/silverpeas/web/usercalendar/socialnetwork/DefaultUserCalendarEventOccurrenceSocialProvider.java
- core-web/src/main/java/org/silverpeas/core/web/calendar/socialnetwork/CalendarEventOccurrenceSocialInformation.java
- core-web/src/main/java/org/silverpeas/core/webapi/calendar/CalendarWebManager.java
The same behavior has been implemented as the one existing until now with old personal calendars.
It means that old events are retrieved when filter is on "All" resources and next events are retrieved when filter is on "Events"...
Don't ask me why.
> Bug #11426: implementing the feed of events from personal calendars.

- core-war/src/main/webapp/attachment/jsp/displayAttachedFiles.jsp
- core-war/src/main/webapp/util/javaScript/silverpeas-view.js
- core-war/src/main/webapp/util/javaScript/silverpeas.js
- core-war/src/main/webapp/util/javaScript/vuejs/silverpeas-vuejs.js
- core-war/src/main/webapp/util/styleSheets/silverpeas-main.css
- core-web/src/main/java/org/silverpeas/core/webapi/attachment/SimpleDocumentEntity.java
Now, the contents are moved according to the new registered sorting of attachments of a block.
Modifications:
- sending a JavaScript custom event just after a successful manual sort of attachemnts
- adding the silverpeas identifier of a simple document to the simple document entity
- modifying the plugin in charge of the display of attachment as content in order to handle the re-sort
- adding new sp.anim with sp.anim.fadeIn feature for now
- making the sorting of attachment as content working even in case of several blocks of attachments are displayed into the same frame
> Improving the attachments as content feature according to the manual sorting of attachments.

- core-api/src/main/java/org/silverpeas/core/util/StringUtil.java
Redefine in StringUtil some of the static methods that are used and that are
declared in the Apache Common Lang3 StringUtils (to satisfy the coding rules
detected by SonarQube when such methods are used by client code).
Don't forget to merge also PR https://github.com/Silverpeas/Silverpeas-Components/pull/695 that contains the bug fix
> Bug #11527

- core-configuration/src/main/config/properties/org/silverpeas/form/settings/types.properties
- core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/TextDisplayer.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/form/record/GenericDataRecord.java
All values of a repeatable field are now well exported (values separated by ' / ')
Fixing another issue at the same time : based-file fields were not exported
> Bug #11570 : Export repeatable field values

- core-api/src/main/java/org/silverpeas/core/calendar/Calendar.java
- core-library/src/main/java/org/silverpeas/core/security/authorization/ComponentAccessController.java
- core-library/src/test/java/org/silverpeas/core/security/authorization/TestComponentAccessController.java
- core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-event-form-main.jsp
- core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-list-item.jsp
- core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-list.jsp
- core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-management.jsp
- core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar.js
- core-war/src/main/webapp/util/javaScript/angularjs/services/calendar/silverpeas-calendar.js
- core-war/src/main/webapp/util/javaScript/silverpeas-calendar.js
- core-war/src/main/webapp/util/javaScript/silverpeas.js
- core-war/src/main/webapp/util/styleSheets/silverpeas-calendar.css
- core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/layout/BodyPartLayoutTag.java
- core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/layout/HtmlLayoutTag.java
- core-web/src/main/java/org/silverpeas/core/webapi/calendar/CalendarWebManager.java
- core-web/src/main/resources/META-INF/viewGenerator.tld
- adding common calendar sorting for JavaScript calendar APIs (wiring Silverpeas's calendar list component)
- it is not possible to modify or delete a calendar displayed from an other component instance than the one it is hosted by
- export a calendar does not open a blank tab anymore- adding a normalization without method directly to JavaScript String instances
- fixing the computing of calendar access about modification operation case (the user MUST be an admin)
- fixing the ComponentAccessController which was authorizing access to a user role into modification context of a component instance
- adding some attributes to view:sp-page & co tags
- refactoring/centralizing some code
Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/694
Checking integration with …
> Feature #10260: creating standard and synchronized calendars from an Almanach instance (without using aggregation).

- core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/PublicationCriteria.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/PublicationDAO.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/PublicationFatherDAO.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/model/PublicationDetail.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/service/DefaultPublicationService.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/service/PublicationService.java
- core-library/src/main/java/org/silverpeas/core/security/authorization/NodeAccessController.java
- core-library/src/main/java/org/silverpeas/core/security/authorization/PublicationAccessController.java
- core-library/src/test/java/org/silverpeas/core/security/authorization/TestPublicationAccessControllerFilter.java
Modifications:
- adding the new criterion and using it on SQL query execution
- adding new attribute into PublicationDetail in order to specify an authorized location which is used for now to compute a right permalink
- taking into account publications aliases into publication service fetching the authorized publication according to given criteria
- fixing a problem around the filtering on authorized publication about caches partially loaded about publication locations
- modifying the service signature about querying of publication locations in order to be as clear as possible
Linked to PR: https://github.com/Silverpeas/Silverpeas-Components/pull/719
> Feature #9047: it is now possible to specify from publication criteria to retrieve publications also from aliases data.

- core-configuration/src/main/config/properties/org/silverpeas/index/indexing/IndexEngine.properties
- core-library/src/main/java/org/silverpeas/core/contribution/publication/service/DefaultPublicationService.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/IndexingLogger.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/model/DidYouMeanIndexer.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/model/FullIndexEntry.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexEntry.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexEntryKey.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexManager.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexProcessor.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexReadersCache.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/model/RepositoryIndexer.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/parser/Parser.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/parser/ParserManager.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/parser/tika/TikaInitialization.java
- core-library/src/main/java/org/silverpeas/core/index/indexing/parser/tika/TikaParser.java
Some of the modifications:
- modifying the indexing file parser in order to provide meta data of files
- avoiding to parse files with mime-type matching a parametrized reg exp pattern
- refactoring clone method to a getCopy one for FullIndexEntry
- centralizing a logger for indexing package (IndexingLogger)
- fixing some sonar feedback
> Bug #11964: avoiding getting errors on file encrypted content during the indexation.

- core-api/src/main/java/org/silverpeas/core/date/Period.java
- core-api/src/main/java/org/silverpeas/core/date/TemporalConverter.java
- core-api/src/main/java/org/silverpeas/core/variables/Variable.java
- core-api/src/test/java/org/silverpeas/core/variables/VariableScheduledValueTest.java
- core-api/src/test/java/org/silverpeas/core/variables/VariableTest.java
- core-war/src/main/java/org/silverpeas/web/variables/VariableUIEntity.java
Fix the conversion from an Instant to a Date object. Java doesn't
correctly take into account the conversion of MIN and MAX values of the
different types of date and datetime, so we have to take ourselves in
charge of these.
> Bug #12446

- core-configuration/src/main/config/properties/org/silverpeas/contribution/multilang/contribution.properties
- core-configuration/src/main/config/properties/org/silverpeas/contribution/multilang/contribution_de.properties
- core-configuration/src/main/config/properties/org/silverpeas/contribution/multilang/contribution_en.properties
- core-configuration/src/main/config/properties/org/silverpeas/contribution/multilang/contribution_fr.properties
- core-library/src/main/java/org/silverpeas/core/contribution/content/form/displayers/ImageFieldDisplayer.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/model/PublicationDetail.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/subscription/AbstractPublicationSubscriptionService.java
- core-library/src/main/java/org/silverpeas/core/contribution/util/ContributionBatchManagementContext.java
- core-library/src/main/java/org/silverpeas/core/contribution/util/ContributionManagementContext.java
- core-library/src/main/java/org/silverpeas/core/subscription/ResourceSubscriptionService.java
- core-library/src/main/java/org/silverpeas/core/subscription/service/AbstractResourceSubscriptionService.java
- core-library/src/main/java/org/silverpeas/core/subscription/service/ResourceSubscriptionProvider.java
- core-war/src/main/webapp/WEB-INF/tags/silverpeas/util/attachmentDragAndDrop.tag
- core-war/src/main/webapp/WEB-INF/tags/silverpeas/util/displayAttachments.tag
- core-war/src/main/webapp/attachment/jsp/displayAttachedFiles.jsp
- core-war/src/main/webapp/contribution/jsp/javaScript/silverpeas-contribution-modification-context.js
- core-war/src/main/webapp/contribution/jsp/messages/modificationContext.jsp
- core-war/src/main/webapp/util/javaScript/silverpeas-subscription.js
- core-war/src/main/webapp/wysiwyg/jsp/htmlEditor.jsp
- core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/buttons/AbstractContributionManagementContextTag.java
- core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/buttons/ContributionBatchManagementContextTag.java
- core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/buttons/ContributionManagementContextTag.java
- core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/layout/BodyPartLayoutTag.java
- core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/layout/HeadLayoutPartTag.java
- core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/layout/HtmlLayoutTag.java
- core-web/src/main/java/org/silverpeas/core/web/util/viewgenerator/html/layout/SilverpeasLayout.java
- core-web/src/main/java/org/silverpeas/core/webapi/subscribe/SubscriptionResource.java
- core-web/src/main/resources/META-INF/viewGenerator.tld
Making the transversal mechanism of popins on contribution modification working on a batch of resources instead of working only on a single one.
A new TAG has been implemented in order to manage a batch of contribution.
Adding the management of a location into mechanism which is checking existence of subscription. It is used for guessing rightly subscriptions into case of an alias.
Fixing a bad behavior on ImageFieldDisplayer which was playing the load of the HTML page as many times as it exists image field.
Cleaning rightly the transversal TAGs written in order to manage the build of a Silverpeas's HTML page.
The Javascript plugins can now working on a single resource or on a batch of resource.
Linked to PR: https://github.com/Silverpeas/Silverpeas-Components/pull/746
> Feature #12035: wiring the modification popins on massive publication update.

- core-library/src/integration-test/java/org/silverpeas/core/subscription/ResourceSubscriptionProviderIT.java
- core-library/src/main/java/org/silverpeas/core/calendar/subscription/AbstractCalendarSubscriptionService.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/subscription/AbstractPublicationSubscriptionService.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/subscription/LocationFilterDirective.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/subscription/OnLocationDirective.java
- core-library/src/main/java/org/silverpeas/core/subscription/ResourceSubscriptionService.java
- core-library/src/main/java/org/silverpeas/core/subscription/SubscriberDirective.java
- core-library/src/main/java/org/silverpeas/core/subscription/service/AbstractResourceSubscriptionService.java
- core-library/src/main/java/org/silverpeas/core/subscription/service/ResourceSubscriptionProvider.java
- core-web/src/main/java/org/silverpeas/core/webapi/subscribe/SubscriptionResource.java
Refactoring centralized services in order to introduce the ability to apply different kinds of directive in the searching for subscribers.
According to the context of the search for subscribers, it is possible to apply a directive that will precise the result.
Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/752
> Bug #12581: fixing the subscription validation popin which was not displayed in some cases when it was supposed to

- core-api/src/main/java/org/silverpeas/core/media/streaming/StreamingProvider.java
- core-api/src/main/java/org/silverpeas/core/media/streaming/StreamingProvidersRegistry.java
- core-configuration/src/main/config/properties/org/silverpeas/media/streaming.properties
- core-library/src/test/java/org/silverpeas/core/media/streaming/StreamingProvidersRegistryTest.java
- core-library/src/test/resources/org/silverpeas/media/streaming.properties
- core-war/src/main/webapp/WEB-INF/tags/silverpeas/media/streamingLibrary.tag
- core-war/src/main/webapp/media/jsp/embedStreaming.jsp
- core-web/src/main/java/org/silverpeas/core/webapi/media/streaming/EmbedStreamingPlayerParams.java
- core-web/src/main/java/org/silverpeas/core/webapi/media/streaming/OembedDataEntity.java
- core-web/src/main/java/org/silverpeas/core/webapi/media/streaming/StreamingPlayerResource.java
- core-web/src/main/java/org/silverpeas/core/webapi/media/streaming/StreamingProviderDataEntity.java
- core-web/src/main/java/org/silverpeas/core/webapi/media/streaming/StreamingProviderDataEntityFactory.java
- core-web/src/main/java/org/silverpeas/core/webapi/media/streaming/StreamingRequester.java
- core-web/src/main/java/org/silverpeas/core/webapi/media/streaming/VimeoDataEntity.java
- core-web/src/main/java/org/silverpeas/core/webapi/media/streaming/YoutubeDataEntity.java
Implementing a registry of streaming provider.
Providers are specified into a property file.
Adding the transversal WEB service which can be used by any module of Silverpeas.
Moving to a centralized place Javascript stuffs permitting to handle Forms dealing with streaming.
Linked to PRs:
* https://github.com/Silverpeas/Silverpeas-Components/pull/767
* https://github.com/Silverpeas/silverpeasmobile/pull/28
> Feature #12789: transversal external streaming player.

- core-api/src/main/java/org/silverpeas/core/util/TriConsumer.java
- core-api/src/main/java/org/silverpeas/core/util/TriFunction.java
- core-library/src/integration-test/java/org/silverpeas/core/admin/StubbedAdministration.java
- core-library/src/main/java/org/silverpeas/core/admin/persistence/ComponentInstanceTable.java
- core-library/src/main/java/org/silverpeas/core/admin/persistence/SpaceUserRoleTable.java
- core-library/src/main/java/org/silverpeas/core/admin/service/Administration.java
- core-library/src/main/java/org/silverpeas/core/admin/service/DefaultAdministration.java
- core-library/src/main/java/org/silverpeas/core/admin/service/RightRecover.java
- core-library/src/main/java/org/silverpeas/core/admin/service/SpaceInstManager.java
- core-library/src/main/java/org/silverpeas/core/admin/space/SpaceInst.java
- core-library/src/main/java/org/silverpeas/core/admin/space/SpaceInstLazyDataLoader.java
- core-library/src/main/java/org/silverpeas/core/admin/space/SpaceProfileInst.java
- core-library/src/test/java/org/silverpeas/core/admin/space/SpaceInstLazyDataLoaderTest.java
Fixing the spreading of space rights which was not merging correctly several space roles on a single instance role.
Fixing the non spreading of specific rights of a space to components and sub spaces when blocking its inheritance.
Adding a mechanism in charge of the lazy loading of some SpaceInst data:
* profiles
* sub spaces
* components
Wiring this mechanism into SpaceInst Object and into services in charge of the feeding of these data.
Fixing little sonarQube feedback.
> Bug #12840: [6.2.x] fixing restoring of a space which was not applying parent space profiles.

- core-api/src/main/java/org/silverpeas/core/util/TriConsumer.java
- core-api/src/main/java/org/silverpeas/core/util/TriFunction.java
- core-library/src/main/java/org/silverpeas/core/admin/persistence/ComponentInstanceTable.java
- core-library/src/main/java/org/silverpeas/core/admin/persistence/SpaceUserRoleTable.java
- core-library/src/main/java/org/silverpeas/core/admin/service/Administration.java
- core-library/src/main/java/org/silverpeas/core/admin/service/DefaultAdministration.java
- core-library/src/main/java/org/silverpeas/core/admin/service/RightRecover.java
- core-library/src/main/java/org/silverpeas/core/admin/service/SpaceInstManager.java
- core-library/src/main/java/org/silverpeas/core/admin/space/SpaceInst.java
- core-library/src/main/java/org/silverpeas/core/admin/space/SpaceInstLazyDataLoader.java
- core-library/src/test/java/org/silverpeas/core/admin/space/SpaceInstLazyDataLoaderTest.java
Fixing the spreading of space rights which was not merging correctly several space roles on a single instance role.
Fixing the non spreading of specific rights of a space to components and sub spaces when blocking its inheritance.
Adding a mechanism in charge of the lazy loading of some SpaceInst data:
* profiles
* sub spaces
* components
Wiring this mechanism into SpaceInst Object and into services in charge of the feeding of these data.
Fixing little sonarQube feedback.
> Bug #12840: [6.3.x] fixing restoring of a space which was not applying parent space profiles.

- core-services/chat/src/main/java/org/silverpeas/core/chat/ChatSettings.java
- core-services/chat/src/main/java/org/silverpeas/core/chat/ChatUser.java
- core-services/chat/src/test/java/org/silverpeas/core/chat/ChatUserLoginTest.java
- core-web/src/test/java/org/silverpeas/core/chat/ChatUserTest.java
- core-web/src/test/resources/org/silverpeas/chat/settings/chat.properties
Format of JID (XMPP identifiers) follows the RFC 7622.
According to this RFC, a JID is formatted as <localpart>@<domainpart>
for a user.
In Silverpeas, the localpart of the JID for a user is computed from his
login. So, when this login is an address email or contains a @
character, the localpart requires to be converted to be compliant with
the RFC. Previously, any part of a login that starts with such a special
character were removed from the login before being used as localpart of
a JID.
Now a new policy is implemented: any @ characters are replaced by a
specific code (for instance its UTF-8 hex equivalent but as word and not
as codepoint, id est 0x40). The policy of the JID formatting is defined
in the properties/org/silverpeas/chat/settings/chat.properties settings
file, under the …
> Bug #13019

- core-configuration/src/main/config/properties/org/silverpeas/authentication/settings/authenticationSettings.properties
- core-configuration/src/main/config/properties/org/silverpeas/multilang/generalMultilang.properties
- core-configuration/src/main/config/properties/org/silverpeas/multilang/generalMultilang_de.properties
- core-configuration/src/main/config/properties/org/silverpeas/multilang/generalMultilang_en.properties
- core-configuration/src/main/config/properties/org/silverpeas/multilang/generalMultilang_fr.properties
- core-library/src/main/java/org/silverpeas/core/security/authentication/Authentication.java
- core-library/src/main/java/org/silverpeas/core/security/authentication/AuthenticationCAS.java
- core-library/src/main/java/org/silverpeas/core/security/authentication/AuthenticationCredential.java
- core-library/src/main/java/org/silverpeas/core/security/authentication/AuthenticationLDAP.java
- core-library/src/main/java/org/silverpeas/core/security/authentication/AuthenticationSQL.java
- core-library/src/main/java/org/silverpeas/core/security/authentication/AuthenticationServer.java
- core-library/src/main/java/org/silverpeas/core/security/authentication/AuthenticationService.java
- core-library/src/main/java/org/silverpeas/core/security/authentication/verifier/AbstractAuthenticationVerifier.java
- core-library/src/test/java/org/silverpeas/core/security/authentication/AuthenticationCredentialTest.java
- core-test/src/main/java/org/silverpeas/core/test/extention/SettingBundleStub.java
- core-war/src/main/webapp/admin/jsp/casAuthenticationError.jsp
Adding loginIgnoreCaseOnUserConnection.default and loginIgnoreCaseOnUserConnection.domainXX parameters into authenticationSettings.properties file.
Implementing the new parameter decoding into AuthenticationCredential class.
Using this new settings into login and user account verifier APIs.
Using this new settings into authentication services.
Fixing displayed page error on authentication problem with CAS SSO.
> Feature #13060: ignoring login case on user authentication when explicitly set into a property file.

- core-api/src/main/java/org/silverpeas/core/calendar/ICalendarEventImportProcessor.java
- core-api/src/main/java/org/silverpeas/core/security/html/HtmlSanitizer.java
- core-library/pom.xml
- core-library/src/integration-test/java/org/silverpeas/core/calendar/CalendarSynchronizationIT.java
- core-library/src/integration-test/java/org/silverpeas/core/calendar/ICalendarEventImportProcessorIT.java
- core-library/src/integration-test/java/org/silverpeas/core/test/WarBuilder4LibCore.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/wysiwyg/service/WysiwygContentTransformer.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/wysiwyg/service/directive/AbstractDirective.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/wysiwyg/service/directive/ImageUrlAccordingToHtmlSizeDirective.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/wysiwyg/service/directive/MailLinkCssApplierDirective.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/wysiwyg/service/directive/OpenLinkOnBlankPageDirective.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/wysiwyg/service/directive/SanitizeDirective.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/wysiwyg/service/directive/SilverpeasLinkCssApplierDirective.java
- core-library/src/main/java/org/silverpeas/core/security/html/DefaultHtmlSanitizer.java
- core-library/src/test/java/org/silverpeas/core/contribution/content/wysiwyg/service/WysiwygContentTransformerTest.java
- core-library/src/test/java/org/silverpeas/core/contribution/content/wysiwyg/service/process/MailContentProcessTest.java
- core-library/src/test/resources/org/silverpeas/core/contribution/content/wysiwyg/service/wysiwygWithFullHtml.txt
- core-library/src/test/resources/org/silverpeas/core/contribution/content/wysiwyg/service/wysiwygWithFullHtmlTransformedBySanitization.txt
- core-library/src/test/resources/org/silverpeas/core/contribution/content/wysiwyg/service/wysiwygWithSeveralTypesOfLinkTransformedForOpeningOnBlankPage.txt
- core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-event-occurrence-list-item.jsp
- core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-event-occurrence-tip.jsp
- core-war/src/main/webapp/util/javaScript/angularjs/directives/calendar/silverpeas-calendar-event-view-main.jsp
- core-war/src/main/webapp/util/javaScript/silverpeas-calendar.js
- core-web/src/main/java/org/silverpeas/core/webapi/calendar/CalendarEventEntity.java
Adding a new HtmlSanitizer API in charge of the sanitizing of an HTML content.
Implementing this new API into library project into which WysiwygContentTransformer has been updated.
Using the new API when synchronizing the description of calendar events.
Adding 2 new directives to WysiwygContentTransformer:
* a directive to transform all links into safe ones by forcing the opening on a new page without any linking with the parent page
* a directive to sanitize an HTML content
Refactoring WysiwygContentTransformer API in order to centralize common code.
AngularJS templates of calendar feature have been modified in order to also perform a sanitize action on HTML on client side (about description data).
Linked to PR https://github.com/Silverpeas/silverpeas-dependencies-bom/pull/38
> Feature #13043: displaying HTML safely for event descriptions of synchronized calendars.

- core-library/src/main/java/org/silverpeas/core/security/authorization/ComponentInstanceSimpleDocumentAccessControlExtension.java
- core-library/src/main/java/org/silverpeas/core/security/authorization/DefaultInstanceAccessControlExtension.java
- core-library/src/main/java/org/silverpeas/core/security/authorization/DefaultInstanceSimpleDocumentAccessControlExtension.java
- core-library/src/main/java/org/silverpeas/core/security/authorization/SimpleDocumentAccessController.java
- core-library/src/test/java/org/silverpeas/core/security/authorization/SimpleDocumentAccessControllerTest.java
Adding ComponentInstanceSimpleDocumentAccessControlExtension API which is an extension dedicated to SimpleDocumentAccessControl API. This extension allows to component implementations to implement some specific behaviors when verifying user authorizations about simple document accesses.
In the case of 'Community' component, anonymous users cannot access an instance of a community. But anonymous user can access the presentation page content and its attached images. To get it possible, the community component has its own implementation of ComponentInstanceSimpleDocumentAccessControlExtension.
Linked to PR https://github.com/Silverpeas/Silverpeas-Components/pull/818
> Bug #13546: fixing to anonymous user an unauthorized access when displaying images from presentation page of a community

- core-library/src/main/java/org/silverpeas/core/contribution/attachment/repository/DocumentConverter.java
When two several threads are switching a same versioned document to a normal one in a same time, the version history of the document can be broken. In a such case, it is no more possible to display the foreign resources linked to a such document in error.
This correction takes into account this case by catching the JCR 2.0 ItemNotFoundException exception as it is already the case with the jackrabbit NoSuchItemStateException one.
> Bug JCR item not found: fixing a technical problem.

- core-api/src/main/java/org/silverpeas/core/security/session/SilverpeasUserSession.java
- core-library/src/main/java/org/silverpeas/core/security/session/SessionInfo.java
- core-library/src/main/java/org/silverpeas/core/security/session/SessionManagement.java
- core-rs/src/main/java/org/silverpeas/core/web/rs/HTTPAuthentication.java
- core-web-test/src/main/java/org/silverpeas/web/test/stub/SessionManagementStub.java
- core-web/src/main/java/org/silverpeas/core/web/session/SessionManager.java
- core-web/src/main/java/org/silverpeas/core/webapi/profile/AuthenticationResource.java
- core-web/src/main/java/org/silverpeas/core/webapi/profile/UserProfileResource.java
A virtual Silverpeas session is created when a user authenticates himself by its API token. This won't then create a true session in Silverpeas.
Don't forget to merge also PR https://github.com/Silverpeas/Silverpeas-Components/pull/832
> Bug #13604 Don't open a Silverpeas session from a successful authentication by the API token

- core-configuration/src/main/config/properties/org/silverpeas/authentication/settings/authenticationSettings.properties
- core-library/src/main/java/org/silverpeas/core/admin/domain/synchro/DefaultSynchroGroupManager.java
- core-library/src/main/java/org/silverpeas/core/admin/domain/synchro/SynchroGroupManager.java
- core-library/src/main/java/org/silverpeas/core/admin/domain/synchro/SynchroGroupScheduler.java
- core-library/src/main/java/org/silverpeas/core/admin/service/DefaultAdministration.java
- core-library/src/main/java/org/silverpeas/core/admin/user/GroupManager.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/credentials/RegistrationSettings.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/credentials/RegistrationUserEventListener.java
Adding a new parameter `registrationSynchroGroupEnabled` into `authenticationSettings.properties` file in order to disabled if needed the synchronization in a such context.
The processing of synchronizing all synchronized group has been extracted from scheduler in charge to trigger the synchronization. Now, it exists a manager of synchronized group which is invoked by the scheduler and also by the new user registration services.
> Feature #14023: synchronize synchronized group on user creation when 'new user registration' feature is enabled

- core-api/src/main/java/org/silverpeas/core/annotation/Bean.java
- core-api/src/main/java/org/silverpeas/core/annotation/Provider.java
- core-api/src/main/java/org/silverpeas/core/annotation/Repository.java
- core-api/src/main/java/org/silverpeas/core/annotation/Service.java
- core-api/src/main/java/org/silverpeas/core/annotation/WebService.java
- core-api/src/main/java/org/silverpeas/core/notification/system/AbstractResourceEvent.java
- core-api/src/main/java/org/silverpeas/core/notification/system/AbstractResourceEventListener.java
- core-api/src/main/java/org/silverpeas/core/notification/system/CDIAfterSuccessfulTransactionResourceEventListener.java
- core-api/src/main/java/org/silverpeas/core/notification/system/CDIResourceEventListener.java
- core-api/src/main/java/org/silverpeas/core/notification/system/CDIResourceEventNotifier.java
- core-api/src/main/java/org/silverpeas/core/notification/system/JMSResourceEventListener.java
- core-api/src/main/java/org/silverpeas/core/notification/system/JMSResourceEventNotifier.java
- core-api/src/main/java/org/silverpeas/core/notification/system/ResourceEvent.java
- core-api/src/main/java/org/silverpeas/core/notification/system/ResourceEventListener.java
- core-api/src/main/java/org/silverpeas/core/notification/system/ResourceEventNotifier.java
- core-library/src/main/java/org/silverpeas/core/admin/service/ComponentInstManager.java
- core-library/src/main/java/org/silverpeas/core/admin/service/DefaultAdministration.java
- core-library/src/main/java/org/silverpeas/core/admin/user/GroupManager.java
- core-library/src/main/java/org/silverpeas/core/admin/user/dao/GroupDAO.java
- core-library/src/main/java/org/silverpeas/core/calendar/notification/AbstractNotifier.java
- core-services/chat/src/main/java/org/silverpeas/core/chat/ChatSettings.java
- core-services/chat/src/main/java/org/silverpeas/core/chat/ChatUsersRegistration.java
- core-services/chat/src/main/java/org/silverpeas/core/chat/listeners/ChatGroupUserLinkEventListener.java
- core-services/chat/src/main/java/org/silverpeas/core/chat/listeners/ChatUserEventListener.java
- core-services/chat/src/main/java/org/silverpeas/core/chat/listeners/RelationShipListener.java
This PR is related to the PR https://github.com/Silverpeas/Silverpeas-Components/pull/851
The method Administration#getGroupByNameInDomain doesn't take into account the specified domain is the mixed one. This peculiar domain hasn't driver so specific code need to be written to take into account of it. In the case the asked group is one of the mixed domain, the method now search directly in Silverpeas without passing through a domain driver to get the specific identifier of asked group in the domain.
> Feature #14033

- core-war/src/main/webapp/util/javaScript/angularjs/controllers/calendar/silverpeas-calendar.js
- core-war/src/main/webapp/util/javaScript/silverpeas-calendar.js
Fix bug: when no non synchronized calendars are visible while asking to create a new event, by default, then, all non synchronized calendars are proposed for the new event. Otherwise, the usual behaviour is played: all the visible non synchronized calendars are proposed (or the default one if one of them is the default calendar).
> Bug #14100

- core-library/src/main/java/org/silverpeas/core/security/authentication/AuthenticationCredential.java
- core-library/src/main/java/org/silverpeas/core/security/authentication/AuthenticationService.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/AuthenticationServlet.java
Fix the vulnerability by defining a dedicated attribute in `AuthenticationCredentials` for authentication successfully performed outside of Silverpeas.
> Bug #14156 Fix the vuln

- core-api/src/main/java/org/silverpeas/core/contribution/model/Thumbnail.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/ddwe/DragAndDropWbeFile.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/ddwe/model/DragAndDropWebEditorStore.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/notification/PublicationEvent.java
- core-library/src/main/java/org/silverpeas/core/io/file/SilverpeasFile.java
- core-library/src/main/java/org/silverpeas/core/io/media/image/thumbnail/control/ThumbnailController.java
- core-library/src/main/java/org/silverpeas/core/io/media/image/thumbnail/model/ThumbnailDetail.java
- core-services/importExport/src/main/java/org/silverpeas/core/importexport/control/RepositoriesTypeManager.java
- core-war/src/main/java/org/silverpeas/web/attachment/DragAndDrop.java
- core-war/src/main/java/org/silverpeas/web/ddwe/DragAndDropWebEditorController.java
- core-war/src/main/webapp/ddwe/jsp/javaScript/silverpeas-ddwe-components.js
In the Drag&Drop Web Edition API, the images as components (a GrapeJS components as GrapJS is used here as the front framework for the API) are treated like attachments to the contribution for which the API is used as editor. But, in the case of a thumbnail uploaded by the user, the image is just a simply link that can be broken when the original thumbnail is deleted or replaced by another image. In order to avoid such issues, and to conform to the way images are treated in the API, now the uploaded thumbnails are now transformed as a simple image component, id est as an attachment to the currently edited contribution through the Drag&Drop Web Edition API.
> Bug #14158

- core-library/src/integration-test/java/org/silverpeas/core/security/authentication/password/service/PasswordRulesServiceIT.java
- core-library/src/main/java/org/silverpeas/core/security/authentication/password/service/DefaultPasswordRulesService.java
- core-library/src/main/java/org/silverpeas/core/security/authentication/password/service/PasswordCheck.java
- core-library/src/main/java/org/silverpeas/core/security/authentication/password/service/PasswordRulesService.java
- core-war/src/main/webapp/password.js
- core-war/src/main/webapp/util/javaScript/silverpeas-password.js
- core-web/src/main/java/org/silverpeas/core/web/authentication/credentials/ChangeCredentialFunctionHandler.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/credentials/ChangeExpiredPasswordHandler.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/credentials/ChangePasswordFunctionHandler.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/credentials/ChangePasswordHandler.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/credentials/EffectiveChangePasswordBeforeExpirationHandler.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/credentials/EffectiveChangePasswordFromLoginHandler.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/credentials/EffectiveChangePasswordHandler.java
- core-web/src/main/java/org/silverpeas/core/webapi/password/PasswordCheckEntity.java
In order to ensure the password to save is the one that was checked, the password that was effectively checked is cached under an auto generated key that is sent back to the client that asked for check. The client, in the case the password satisfied all the password rules, sends to the server the check key with the password to save. If the key doesn't match any cache entry or if the password in the cache (hence the checked password) doesn't match the password to save, then an Authentication exception is thrown.
> Bug #14277 Cache the checked password to ensure this one is effectively the password to save

- core-war/src/main/java/org/silverpeas/web/jobstartpage/servlets/JobStartPagePeasRequestRouter.java
- core-web/src/main/java/org/silverpeas/core/web/mvc/route/AdminComponentRequestRouter.java
In JobStartPageRequestRouter, when creating a root space, no space has been yet set as current space (because there is no parent space to a root space): this causes a NullPointerException. It was a regression introduced by the fix of the bug #13761. Restores the check of nullity of the current space in the setSpaceInfosInRequest method.
> Bug #14397

- core-api/src/main/java/org/silverpeas/core/admin/user/model/SilverpeasRole.java
- core-war/src/main/java/org/silverpeas/web/AutoRedirectServlet.java
- core-war/src/main/webapp/admin/jsp/silverpeas-body-part.jsp
- core-war/src/main/webapp/admin/jsp/silverpeas-main.jsp
- core-web/src/main/java/org/silverpeas/core/web/authentication/AuthenticationServlet.java
- core-web/src/main/java/org/silverpeas/core/web/authentication/SilverpeasSessionOpener.java
- core-web/src/main/java/org/silverpeas/core/web/session/HTTPSessionInfo.java
- core-web/src/main/java/org/silverpeas/core/web/util/WebRedirection.java
In anonymous mode, the redirection to the contribution referred by a notification wasn't done correctly when the user isn't authenticated:
* if the user isn't connected, it recieves an access forbidden (normal as it is not yet connected)
* and once he signs in, he's redirected into the main page instead of the contribution.
Now, when the user accesses from the notification (email) to Silverpeas, he's automatically redirected into the login page for authentication. Once authenticated, he's redirected into the page in which is displayed the contribution referred by the notification.
For doing, in the authentication process, in the session is opening, the computation of a possible redirection URL takes into account now of the parameters of redirection. Those parameters are set by …
> Bug #14387

- core-api/src/main/java/org/silverpeas/core/ResourceReference.java
- core-library/src/integration-test/java/org/silverpeas/core/contribution/publication/service/PublicationDAOIT.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/dao/PublicationDAO.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/model/PublicationDetail.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/model/PublicationIdentifier.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/model/PublicationPK.java
- core-library/src/main/java/org/silverpeas/core/contribution/publication/service/DefaultPublicationService.java
- core-library/src/main/java/org/silverpeas/core/index/search/SimpleSearchEngine.java
- core-library/src/main/java/org/silverpeas/core/security/authorization/PublicationAccessController.java
- core-library/src/test/java/org/silverpeas/core/security/authorization/PublicationDetail4Test.java
A publication is a peculiar contribution in Silverpeas as it can be located in several locations in the same or in different component instances. In this case, we have the original publication along with its all aliases. This capability is used in the Kmelia application. As consequence, the publication is only referred uniquely by its local identifier (its local identifier is its global one), whereas the others types of contributions are identified uniquely by their global identifier that is made up of their local identifier and of the identifier of the application instance they belong to.
Despite this peculiarity, the indexation, the search and the access rights computation treat the publications only by their local identifier, and this can cause troubles when the aliases of a …
> Bug #14471

- core-library/src/main/java/org/silverpeas/core/node/dao/NodeDAO.java
- core-library/src/main/java/org/silverpeas/core/node/model/NodeDetail.java
- core-library/src/main/java/org/silverpeas/core/node/service/DefaultNodeService.java
The move of a node was done by deleting and then recreating in database the node with its new location, and this without updating its translations to refer the correct new node.
Replace the deletion and then the creation of the moved node by a simple suitable update: in fact, a move method already existed in the NodeDAO but it wasn't anymore used. This method update accordingly a node details in the database for a node move. The translations of the node are then not lost.
Refine the update of a node in DefaultNodeService by avoiding to retrieve again from the database the current node before update; Get it at first, then use it all along the update process.
Don't forget to take into account also the PR https://github.com/Silverpeas/Silverpeas-Components/pull/867
> Bug #14503

- core-library/src/main/java/org/silverpeas/core/admin/service/AdminController.java
- core-library/src/main/java/org/silverpeas/core/admin/service/Administration.java
- core-library/src/main/java/org/silverpeas/core/admin/service/DefaultAdministration.java
to indicate if the synchronization has to be forced, even when no changes are detected. If this parameter is valued at true, and in the case of no changes, then the user is indexed again.
> Bug #14518 Add in Administration#synchronizeUser a new boolean parameter

- core-library/src/integration-test/java/org/silverpeas/core/admin/SpacesAndComponentsIT.java
- core-library/src/main/java/org/silverpeas/core/admin/service/Administration.java
- core-library/src/main/java/org/silverpeas/core/admin/service/DefaultAdministration.java
- core-library/src/main/java/org/silverpeas/core/admin/service/SpaceProfile.java
- core-library/src/main/java/org/silverpeas/core/admin/space/SpaceInst.java
- core-library/src/main/java/org/silverpeas/core/admin/user/model/UserDetail.java
- core-war/src/main/java/org/silverpeas/web/jobstartpage/control/JobStartPagePeasSessionController.java
- core-war/src/main/webapp/jobStartPagePeas/jsp/startPageInfo.jsp
- core-war/src/main/webapp/util/javaScript/silverpeas-responsibles.js
- core-web/src/main/java/org/silverpeas/core/web/look/DefaultSpaceHomePage.java
- core-web/src/main/java/org/silverpeas/core/webapi/admin/SpaceResource.java
Rename SpaceInst#getSpaceProfileInst to
SpaceProfilInst#getDirectSpaceProfileInst because this method returns only the direct space profile instance with the specified name and not all the profile instances (both inherited and not inherited).
Add new method to get both the inherited and direct space profiles with a specified name: SpaceInst#getSpaceProfileInst(String)
In DefaultAdministration:
- when a new space is created, in the case of a inherited rights access, the inherited space manager profile is now taken into account in same way than the others inherited space profiles.
- when getting the space profile of a given space and with the specified role name, take into account the inherited space manager profile has been previously cached
In SpaceResource, when getting the space …
> Bug #13273

- core-configuration/src/main/config/properties/org/silverpeas/admin/admin.properties
- core-configuration/src/main/config/properties/org/silverpeas/jobStartPagePeas/multilang/jobStartPagePeasBundle.properties
- core-configuration/src/main/config/properties/org/silverpeas/jobStartPagePeas/multilang/jobStartPagePeasBundle_de.properties
- core-configuration/src/main/config/properties/org/silverpeas/jobStartPagePeas/multilang/jobStartPagePeasBundle_en.properties
- core-configuration/src/main/config/properties/org/silverpeas/jobStartPagePeas/multilang/jobStartPagePeasBundle_fr.properties
- core-library/src/main/java/org/silverpeas/core/admin/AdminSettings.java
- core-library/src/main/java/org/silverpeas/core/admin/service/DeleteRemovedApplicationsScheduler.java
- core-library/src/main/java/org/silverpeas/core/admin/service/DeleteRemovedSpacesScheduler.java
- core-war/src/main/webapp/jobStartPagePeas/jsp/bin.jsp
Implement the feature by following the same mechanism used for both
removed users and groups: the delay in days since the removal of a space
or of a component instance after which this space or application is
definitively deleted is specified into the
`org/silverpeas/admin/admin.properties` configurartion file. Two delays
and two CRONs can be set: one for the removed spaces and another one for
the removed applications.
> Feature 10785

- core-war/src/main/java/org/silverpeas/web/directory/servlets/DirectoryRequestRouter.java
Fix the bug. The access to the directory shouldn't be conditionned by the enabling of the directory access entry in the banner.
> Bug #14659

- core-library/src/main/java/org/silverpeas/core/contribution/content/form/FieldTemplate.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/form/FieldValueTemplate.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/form/dummy/DummyFieldTemplate.java
- core-library/src/main/java/org/silverpeas/core/contribution/content/form/record/GenericFieldTemplate.java
- core-services/workflow/src/main/java/org/silverpeas/core/workflow/engine/datarecord/ProcessInstanceFieldTemplate.java
Add FieldValueTemplate to model the template of a field value in a RecordTemplate of a form. This is to avoid to parse template parameters for both keys and values of fields in a FieldTemplate; the way they are encoded in the FieldTemplate has to be encapsulated and not exposed.
> Bug #14806
